/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Shared.TrigonometricBernstein

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap42Tail

abbrev degree : ℕ := 5

abbrev tailPower : List ℚ :=
  [
    (-11180 : ℚ), (14625997 / 32000 : ℚ), (-447858 / 625 : ℚ),
    (1616423 / 5000 : ℚ), (-832 / 25 : ℚ), (1 : ℚ)
  ]

abbrev shiftedPower : List ℚ :=
  [
    (44020033 / 10000 : ℚ), (1316765697 / 160000 : ℚ), (580376 / 125 : ℚ),
    (3766823 / 5000 : ℚ), (1168 / 25 : ℚ), (1 : ℚ)
  ]

private def tailLeaf00Bernstein : List ℚ :=
  [
    (19227779 / 80000 : ℚ), (151659291 / 32000 : ℚ), (188470669 / 20000 : ℚ),
    (2055991449 / 160000 : ℚ), (1053251973 / 80000 : ℚ), (1797232043 / 160000 : ℚ)
  ]

theorem tailLeaf00IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (6 : ℚ) (11 : ℚ)
      degree tailLeaf00Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf00NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf00Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf00Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (6 : ℚ) (11 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf00Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf00Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf00IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf00Nonneg {y : ℝ}
    (hlo : (((6 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((11 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf00Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf00NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf00Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (6 : ℚ) (11 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf00Nonneg hlo hhi)
private def tailLeaf01Bernstein : List ℚ :=
  [
    (1797232043 / 160000 : ℚ), (3285192183 / 320000 : ℚ), (34950351 / 4000 : ℚ),
    (2161454077 / 320000 : ℚ), (735126237 / 160000 : ℚ), (896755571 / 320000 : ℚ)
  ]

theorem tailLeaf01IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (11 : ℚ) (27 / 2 : ℚ)
      degree tailLeaf01Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf01NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf01Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf01Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (11 : ℚ) (27 / 2 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf01Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf01Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf01IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf01Nonneg {y : ℝ}
    (hlo : (((11 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((27 / 2 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf01Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf01NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf01Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (11 : ℚ) (27 / 2 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf01Nonneg hlo hhi)
private def tailLeaf02Bernstein : List ℚ :=
  [
    (896755571 / 320000 : ℚ), (1220014239 / 640000 : ℚ), (352684843 / 320000 : ℚ),
    (146580279 / 320000 : ℚ), (117699 / 2000 : ℚ), (22667 / 2500 : ℚ)
  ]

theorem tailLeaf02IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (27 / 2 : ℚ) (59 / 4 : ℚ)
      degree tailLeaf02Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf02NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf02Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf02Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (27 / 2 : ℚ) (59 / 4 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf02Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf02Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf02IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf02Nonneg {y : ℝ}
    (hlo : (((27 / 2 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((59 / 4 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf02Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf02NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf02Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (27 / 2 : ℚ) (59 / 4 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf02Nonneg hlo hhi)
private def tailLeaf03Bernstein : List ℚ :=
  [
    (22667 / 2500 : ℚ), (227517 / 80000 : ℚ), (8523723 / 4096000 : ℚ),
    (571974337 / 81920000 : ℚ), (46547301723 / 2621440000 : ℚ), (725987832221 / 20971520000 : ℚ)
  ]

theorem tailLeaf03IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (59 / 4 : ℚ) (477 / 32 : ℚ)
      degree tailLeaf03Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf03NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf03Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf03Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (59 / 4 : ℚ) (477 / 32 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf03Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf03Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf03IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf03Nonneg {y : ℝ}
    (hlo : (((59 / 4 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((477 / 32 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf03Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf03NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf03Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (59 / 4 : ℚ) (477 / 32 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf03Nonneg hlo hhi)
private def tailLeaf04Bernstein : List ℚ :=
  [
    (725987832221 / 20971520000 : ℚ), (539798625329 / 10485760000 : ℚ), (78043155201 / 1048576000 : ℚ),
    (271784101529 / 2621440000 : ℚ), (182776057709 / 1310720000 : ℚ), (119249720833 / 655360000 : ℚ)
  ]

theorem tailLeaf04IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (477 / 32 : ℚ) (241 / 16 : ℚ)
      degree tailLeaf04Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf04NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf04Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf04Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (477 / 32 : ℚ) (241 / 16 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf04Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf04Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf04IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf04Nonneg {y : ℝ}
    (hlo : (((477 / 32 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((241 / 16 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf04Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf04NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf04Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (477 / 32 : ℚ) (241 / 16 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf04Nonneg hlo hhi)
private def tailLeaf05Bernstein : List ℚ :=
  [
    (119249720833 / 655360000 : ℚ), (17497310479 / 65536000 : ℚ), (62093810693 / 163840000 : ℚ),
    (42578755263 / 81920000 : ℚ), (28310246921 / 40960000 : ℚ), (18333059699 / 20480000 : ℚ)
  ]

theorem tailLeaf05IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (241 / 16 : ℚ) (123 / 8 : ℚ)
      degree tailLeaf05Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf05NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf05Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf05Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (241 / 16 : ℚ) (123 / 8 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf05Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf05Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf05IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf05Nonneg {y : ℝ}
    (hlo : (((241 / 16 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((123 / 8 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf05Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf05NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf05Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (241 / 16 : ℚ) (123 / 8 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf05Nonneg hlo hhi)
private def tailLeaf06Bernstein : List ℚ :=
  [
    (18333059699 / 20480000 : ℚ), (1668058261 / 1280000 : ℚ), (9428702757 / 5120000 : ℚ),
    (323318323 / 128000 : ℚ), (4317798527 / 1280000 : ℚ), (44020033 / 10000 : ℚ)
  ]

theorem tailLeaf06IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (123 / 8 : ℚ) (16 : ℚ)
      degree tailLeaf06Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf06NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf06Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf06Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (123 / 8 : ℚ) (16 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf06Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf06Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf06IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf06Nonneg {y : ℝ}
    (hlo : (((123 / 8 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((16 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf06Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf06NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf06Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (123 / 8 : ℚ) (16 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf06Nonneg hlo hhi)

theorem coreTree :
    NonnegativeTree (rationalPowerValue tailPower)
      (6 : ℚ) (16 : ℚ) := by
  exact .branch
      ((by
        convert tailLeaf00Tree using 1
        all_goals norm_num))
      (.branch
      ((by
        convert tailLeaf01Tree using 1
        all_goals norm_num))
      (.branch
      ((by
        convert tailLeaf02Tree using 1
        all_goals norm_num))
      (.branch
      (.branch
      (.branch
      ((by
        convert tailLeaf03Tree using 1
        all_goals norm_num))
      ((by
        convert tailLeaf04Tree using 1
        all_goals norm_num)))
      ((by
        convert tailLeaf05Tree using 1
        all_goals norm_num)))
      ((by
        convert tailLeaf06Tree using 1
        all_goals norm_num)))))

theorem coreNonnegative {x : ℝ}
    (hlo : (((6 : ℚ)) : ℝ) ≤ x) (hhi : x ≤ (16 : ℝ)) :
    0 ≤ rationalPowerValue tailPower x :=
  coreTree.nonneg hlo hhi

theorem shiftedIdentity (t : ℝ) :
    rationalPowerValue tailPower (16 + t) =
      rationalPowerValue shiftedPower t := by
  norm_num [rationalPowerValue, powerPolynomialQ, tailPower, shiftedPower,
    Finset.sum_range_succ]
  ring

theorem shiftedNonnegative {t : ℝ} (ht : 0 ≤ t) :
    0 ≤ rationalPowerValue shiftedPower t := by
  norm_num [rationalPowerValue, powerPolynomialQ, shiftedPower,
    Finset.sum_range_succ]
  positivity

theorem nonnegativeAbove {x : ℝ} (hx : (((6 : ℚ)) : ℝ) ≤ x) :
    0 ≤ rationalPowerValue tailPower x := by
  by_cases hcore : x ≤ 16
  · exact coreNonnegative hx hcore
  · have ht : 0 ≤ x - 16 := by linarith
    rw [show x = 16 + (x - 16) by ring, shiftedIdentity]
    exact shiftedNonnegative ht

end CertifiedJL.TernaryLInfTwoDecimal.Cap42Tail
