/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_04_chunk_000 :
    boxCellChunk (profileBox 4) 0 25 =
      ⟨0,
        597158215931848019714361063733586411301795695609452848787108225301217497311353755138836953809553994315171069329099752258325281044606252982285362274409653⟩ := by
  decide +kernel

theorem box_04_chunk_001 :
    boxCellChunk (profileBox 4) 25 25 =
      ⟨0,
        5818779403597109897488053363350855618386445401608956913594275442949596367420530007269041519148086530304590154611144320287166388472329156⟩ := by
  decide +kernel

theorem box_04_chunk_002 :
    boxCellChunk (profileBox 4) 50 25 =
      ⟨0,
        70235792986483265495366976670945399583238114872695730064685604525858949605503313309103705031175195263983⟩ := by
  decide +kernel

theorem box_04_chunk_003 :
    boxCellChunk (profileBox 4) 75 25 =
      ⟨0,
        81437838722002943793045913207467305459339672352952512845984960178012629547⟩ := by
  decide +kernel

theorem box_04_chunk_004 :
    boxCellChunk (profileBox 4) 100 25 =
      ⟨0,
        325682936710206024078222320380316810258976143178707⟩ := by
  decide +kernel

theorem box_04_chunk_005 :
    boxCellChunk (profileBox 4) 125 25 =
      ⟨0,
        1508933043452347321189234615971936035⟩ := by
  decide +kernel

theorem box_04_chunk_006 :
    boxCellChunk (profileBox 4) 150 25 =
      ⟨0,
        373365609984384043048300485316501848963724634153028232⟩ := by
  decide +kernel

theorem box_04_chunk_007 :
    boxCellChunk (profileBox 4) 175 25 =
      ⟨0,
        11273506386599954421288488640069861697695184774724524955715474396778997046296956101784974585119919336⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
