import CertifiedJL.Certificates.Families.L2Lower.Rows256Bits128.Near.Data.ThresholdNearCoarsePlan128

/-! Generated by scripts/GenerateNearCoarsePlans.lean. Raw proposals only.
Every production leaf still requires a kernel proof of planCheck = true. -/

namespace CertifiedJL.ThresholdNearCoarse128

set_option linter.style.longLine false

def storedPlans : List (Cell × Plan) := [
  -- ThresholdNearCoarseShard0000_00_00_0000_128
  ({ xLower := (1 / 1), xUpper := (162401 / 160000), aLower := (9 / 16), aUpper := (363979 / 640000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX .leaf .leaf) .leaf) .leaf)) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0000_00_00_0001_128
  ({ xLower := (1 / 1), xUpper := (162401 / 160000), aLower := (363979 / 640000), aUpper := (183979 / 320000) }, (.splitX (.splitA (.splitX (.splitA .leaf .leaf) .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0000_00_00_0010_128
  ({ xLower := (162401 / 160000), xUpper := (82401 / 80000), aLower := (9 / 16), aUpper := (363979 / 640000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0000_00_00_0011_128
  ({ xLower := (162401 / 160000), xUpper := (82401 / 80000), aLower := (363979 / 640000), aUpper := (183979 / 320000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0000_00_00_01_128
  ({ xLower := (1 / 1), xUpper := (82401 / 80000), aLower := (183979 / 320000), aUpper := (93979 / 160000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf))) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0000_00_00_10_128
  ({ xLower := (82401 / 80000), xUpper := (42401 / 40000), aLower := (9 / 16), aUpper := (183979 / 320000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0000_00_00_11_128
  ({ xLower := (82401 / 80000), xUpper := (42401 / 40000), aLower := (183979 / 320000), aUpper := (93979 / 160000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0000_00_01_128
  ({ xLower := (1 / 1), xUpper := (42401 / 40000), aLower := (93979 / 160000), aUpper := (48979 / 80000) }, (.splitX (.splitA (.splitX (.splitA (.splitX (.splitA .leaf .leaf) .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX (.splitA .leaf .leaf) .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf))) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0000_00_10_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (9 / 16), aUpper := (93979 / 160000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0000_00_11_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (93979 / 160000), aUpper := (48979 / 80000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0000_01_00_128
  ({ xLower := (1 / 1), xUpper := (42401 / 40000), aLower := (48979 / 80000), aUpper := (101937 / 160000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX .leaf .leaf) .leaf) (.splitA .leaf .leaf))) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0000_01_01_128
  ({ xLower := (1 / 1), xUpper := (42401 / 40000), aLower := (101937 / 160000), aUpper := (26479 / 40000) }, (.splitX (.splitA (.splitX (.splitA .leaf .leaf) .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA (.splitX .leaf .leaf) .leaf))),
  -- ThresholdNearCoarseShard0000_01_10_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (48979 / 80000), aUpper := (101937 / 160000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0000_01_11_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (101937 / 160000), aUpper := (26479 / 40000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0000_10_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (9 / 16), aUpper := (48979 / 80000) }, (.splitX (.splitA (.splitX .leaf .leaf) .leaf) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0000_11_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (48979 / 80000), aUpper := (26479 / 40000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0001_0000_128
  ({ xLower := (1 / 1), xUpper := (42401 / 40000), aLower := (26479 / 40000), aUpper := (21979 / 32000) }, (.splitX (.splitA (.splitX (.splitA .leaf .leaf) .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0001_0001_128
  ({ xLower := (1 / 1), xUpper := (42401 / 40000), aLower := (21979 / 32000), aUpper := (56937 / 80000) }, (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0001_0010_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (26479 / 40000), aUpper := (21979 / 32000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0001_0011_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (21979 / 32000), aUpper := (56937 / 80000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0001_01_128
  ({ xLower := (1 / 1), xUpper := (22401 / 20000), aLower := (56937 / 80000), aUpper := (15229 / 20000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf))) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0001_10_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (26479 / 40000), aUpper := (56937 / 80000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0001_11_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (56937 / 80000), aUpper := (15229 / 20000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0010_128
  ({ xLower := (12401 / 10000), xUpper := (7401 / 5000), aLower := (9 / 16), aUpper := (26479 / 40000) }, (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0011_128
  ({ xLower := (12401 / 10000), xUpper := (7401 / 5000), aLower := (26479 / 40000), aUpper := (15229 / 20000) }, (.splitX (.splitA (.splitX .leaf .leaf) .leaf) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0100_00_128
  ({ xLower := (1 / 1), xUpper := (22401 / 20000), aLower := (15229 / 20000), aUpper := (12979 / 16000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf))) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0100_01_128
  ({ xLower := (1 / 1), xUpper := (22401 / 20000), aLower := (12979 / 16000), aUpper := (34437 / 40000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) (.splitA .leaf .leaf))) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0100_10_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (15229 / 20000), aUpper := (12979 / 16000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0100_11_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (12979 / 16000), aUpper := (34437 / 40000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0101_00_128
  ({ xLower := (1 / 1), xUpper := (22401 / 20000), aLower := (34437 / 40000), aUpper := (72853 / 80000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf)) (.splitX (.splitA (.splitX (.splitA .leaf .leaf) .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf))) (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0101_01_00_128
  ({ xLower := (1 / 1), xUpper := (42401 / 40000), aLower := (72853 / 80000), aUpper := (29937 / 32000) }, (.splitX (.splitA (.splitX (.splitA (.splitX .leaf .leaf) (.splitX .leaf .leaf)) .leaf) (.splitX (.splitA (.splitX .leaf .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf))) (.splitA .leaf (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0101_01_01_00_128
  ({ xLower := (1 / 1), xUpper := (82401 / 80000), aLower := (29937 / 32000), aUpper := (303349 / 320000) }, (.splitX (.splitA (.splitX (.splitA .leaf .leaf) .leaf) (.splitX (.splitA .leaf (.splitX .leaf .leaf)) .leaf)) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0101_01_01_0100_128
  ({ xLower := (1 / 1), xUpper := (162401 / 160000), aLower := (303349 / 320000), aUpper := (610677 / 640000) }, (.splitX (.splitA (.splitX .leaf .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0101_01_01_0101_128
  ({ xLower := (1 / 1), xUpper := (162401 / 160000), aLower := (610677 / 640000), aUpper := (2401 / 2500) }, (.splitX (.splitA (.splitX (.splitA .leaf (.splitX .leaf .leaf)) .leaf) (.splitX (.splitA (.splitX .leaf .leaf) (.splitX (.splitA .leaf .leaf) .leaf)) (.splitA .leaf .leaf))) (.splitA .leaf (.splitX .leaf .leaf)))),
  -- ThresholdNearCoarseShard0101_01_01_0110_128
  ({ xLower := (162401 / 160000), xUpper := (82401 / 80000), aLower := (303349 / 320000), aUpper := (610677 / 640000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0101_01_01_0111_128
  ({ xLower := (162401 / 160000), xUpper := (82401 / 80000), aLower := (610677 / 640000), aUpper := (2401 / 2500) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0101_01_01_10_128
  ({ xLower := (82401 / 80000), xUpper := (42401 / 40000), aLower := (29937 / 32000), aUpper := (303349 / 320000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0101_01_01_11_128
  ({ xLower := (82401 / 80000), xUpper := (42401 / 40000), aLower := (303349 / 320000), aUpper := (2401 / 2500) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0101_01_10_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (72853 / 80000), aUpper := (29937 / 32000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard0101_01_11_128
  ({ xLower := (42401 / 40000), xUpper := (22401 / 20000), aLower := (29937 / 32000), aUpper := (2401 / 2500) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0101_10_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (34437 / 40000), aUpper := (72853 / 80000) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0101_11_128
  ({ xLower := (22401 / 20000), xUpper := (12401 / 10000), aLower := (72853 / 80000), aUpper := (2401 / 2500) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard0110_128
  ({ xLower := (12401 / 10000), xUpper := (7401 / 5000), aLower := (15229 / 20000), aUpper := (34437 / 40000) }, (.splitX (.splitA .leaf .leaf) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard0111_128
  ({ xLower := (12401 / 10000), xUpper := (7401 / 5000), aLower := (34437 / 40000), aUpper := (2401 / 2500) }, (.splitX (.splitA .leaf .leaf) .leaf)),
  -- ThresholdNearCoarseShard1000_128
  ({ xLower := (7401 / 5000), xUpper := (17203 / 10000), aLower := (9 / 16), aUpper := (26479 / 40000) }, (.splitX (.splitA .leaf .leaf) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard1001_128
  ({ xLower := (7401 / 5000), xUpper := (17203 / 10000), aLower := (26479 / 40000), aUpper := (15229 / 20000) }, (.splitX (.splitA .leaf .leaf) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard1010_128
  ({ xLower := (17203 / 10000), xUpper := (4901 / 2500), aLower := (9 / 16), aUpper := (26479 / 40000) }, (.splitX (.splitA .leaf .leaf) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard1011_128
  ({ xLower := (17203 / 10000), xUpper := (4901 / 2500), aLower := (26479 / 40000), aUpper := (15229 / 20000) }, (.splitX (.splitA .leaf .leaf) (.splitA .leaf .leaf))),
  -- ThresholdNearCoarseShard1100_128
  ({ xLower := (7401 / 5000), xUpper := (17203 / 10000), aLower := (15229 / 20000), aUpper := (34437 / 40000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard1101_128
  ({ xLower := (7401 / 5000), xUpper := (17203 / 10000), aLower := (34437 / 40000), aUpper := (2401 / 2500) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard1110_128
  ({ xLower := (17203 / 10000), xUpper := (4901 / 2500), aLower := (15229 / 20000), aUpper := (34437 / 40000) }, (.splitX .leaf .leaf)),
  -- ThresholdNearCoarseShard1111_128
  ({ xLower := (17203 / 10000), xUpper := (4901 / 2500), aLower := (34437 / 40000), aUpper := (2401 / 2500) }, (.splitX .leaf .leaf))]

/-- A missing proposal returns a leaf, which must still pass the checker. -/
def storedPlan (cell : Cell) : Plan :=
  match storedPlans.find? (fun entry => decide (entry.1 = cell)) with
  | some entry => entry.2
  | none => .leaf

end CertifiedJL.ThresholdNearCoarse128
