/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Shared.TrigonometricBernstein

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap47Tail

abbrev degree : ℕ := 5

abbrev tailPower : List ℚ :=
  [
    (-9460 : ℚ), (14625997 / 32000 : ℚ), (-447858 / 625 : ℚ),
    (1616423 / 5000 : ℚ), (-832 / 25 : ℚ), (1 : ℚ)
  ]

abbrev shiftedPower : List ℚ :=
  [
    (61220033 / 10000 : ℚ), (1316765697 / 160000 : ℚ), (580376 / 125 : ℚ),
    (3766823 / 5000 : ℚ), (1168 / 25 : ℚ), (1 : ℚ)
  ]

private def tailLeaf00Bernstein : List ℚ :=
  [
    (1391863372147972149 / 100000000000000000000 : ℚ), (912052880461347122387189 / 200000000000000000000 : ℚ), (3890373505753243042776229 / 400000000000000000000 : ℚ),
    (11171691047748221709139269 / 800000000000000000000 : ℚ), (23886373326587107421476309 / 1600000000000000000000 : ℚ), (42670628532542386979787349 / 3200000000000000000000 : ℚ)
  ]

theorem tailLeaf00IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (55589 / 10000 : ℚ) (215589 / 20000 : ℚ)
      degree tailLeaf00Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf00NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf00Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf00Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (55589 / 10000 : ℚ) (215589 / 20000 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf00Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf00Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf00IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf00Nonneg {y : ℝ}
    (hlo : (((55589 / 10000 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((215589 / 20000 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf00Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf00NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf00Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (55589 / 10000 : ℚ) (215589 / 20000 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf00Nonneg hlo hhi)
private def tailLeaf01Bernstein : List ℚ :=
  [
    (42670628532542386979787349 / 3200000000000000000000 : ℚ), (80239138944452946096409429 / 6400000000000000000000 : ℚ), (142085941064829080596927509 / 12800000000000000000000 : ℚ),
    (233300700415850684881341589 / 25600000000000000000000 : ℚ), (351066528441804253349651669 / 51200000000000000000000 : ℚ), (504250393069082880401857749 / 102400000000000000000000 : ℚ)
  ]

theorem tailLeaf01IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (215589 / 20000 : ℚ) (535589 / 40000 : ℚ)
      degree tailLeaf01Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf01NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf01Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf01Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (215589 / 20000 : ℚ) (535589 / 40000 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf01Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf01Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf01IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf01Nonneg {y : ℝ}
    (hlo : (((215589 / 20000 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((535589 / 40000 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf01Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf01NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf01Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (215589 / 20000 : ℚ) (535589 / 40000 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf01Nonneg hlo hhi)
private def tailLeaf02Bernstein : List ℚ :=
  [
    (504250393069082880401857749 / 102400000000000000000000 : ℚ), (14959361780007678423067 / 5000000000000000000 : ℚ), (4427254575165632322987 / 3200000000000000000 : ℚ),
    (1385463738498921 / 2000000000000 : ℚ), (58419282410533 / 32000000000 : ℚ), (61220033 / 10000 : ℚ)
  ]

theorem tailLeaf02IdentityCheck :
    bernsteinIdentityBlockCheck tailPower (535589 / 40000 : ℚ) (16 : ℚ)
      degree tailLeaf02Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf02NonnegativeCheck :
    nonnegativeBlockCheck tailLeaf02Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem tailLeaf02Identity :
    affinePullbackQ (powerPolynomialQ tailPower) (535589 / 40000 : ℚ) (16 : ℚ) =
      bernsteinPolynomialQ degree tailLeaf02Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ (by simp [degree, tailPower])
    (by simp [degree, tailLeaf02Bernstein])
  intro k hk
  exact bernsteinIdentityBlockCheck_sound tailLeaf02IdentityCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem tailLeaf02Nonneg {y : ℝ}
    (hlo : (((535589 / 40000 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((16 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue tailPower y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi tailLeaf02Identity
  intro k hk
  exact nonnegativeBlockCheck_sound tailLeaf02NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem tailLeaf02Tree :
    NonnegativeTree (rationalPowerValue tailPower)
      (535589 / 40000 : ℚ) (16 : ℚ) :=
  .leaf (fun _y hlo hhi => tailLeaf02Nonneg hlo hhi)

theorem coreTree :
    NonnegativeTree (rationalPowerValue tailPower)
      (55589 / 10000 : ℚ) (16 : ℚ) := by
  exact .branch
      ((by
        convert tailLeaf00Tree using 1
        all_goals norm_num))
      (.branch
      ((by
        convert tailLeaf01Tree using 1
        all_goals norm_num))
      ((by
        convert tailLeaf02Tree using 1
        all_goals norm_num)))

theorem coreNonnegative {x : ℝ}
    (hlo : (((55589 / 10000 : ℚ)) : ℝ) ≤ x) (hhi : x ≤ (16 : ℝ)) :
    0 ≤ rationalPowerValue tailPower x :=
  coreTree.nonneg hlo hhi

theorem shiftedIdentity (t : ℝ) :
    rationalPowerValue tailPower (16 + t) =
      rationalPowerValue shiftedPower t := by
  norm_num [rationalPowerValue, powerPolynomialQ, tailPower, shiftedPower,
    Finset.sum_range_succ]
  ring

theorem shiftedNonnegative {t : ℝ} (ht : 0 ≤ t) :
    0 ≤ rationalPowerValue shiftedPower t := by
  norm_num [rationalPowerValue, powerPolynomialQ, shiftedPower,
    Finset.sum_range_succ]
  positivity

theorem nonnegativeAbove {x : ℝ} (hx : (((55589 / 10000 : ℚ)) : ℝ) ≤ x) :
    0 ≤ rationalPowerValue tailPower x := by
  by_cases hcore : x ≤ 16
  · exact coreNonnegative hx hcore
  · have ht : 0 ≤ x - 16 := by linarith
    rw [show x = 16 + (x - 16) by ring, shiftedIdentity]
    exact shiftedNonnegative ht

end CertifiedJL.TernaryLInfTwoDecimal.Cap47Tail
