/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_00_chunk_000 :
    boxCellChunk (profileBox 0) 0 25 =
      ⟨0,
        880748663211978263785093780922054020250716698534236190226803919898679037750006657597669369859055513372211897982427915846257663234812016282284330490340824⟩ := by
  decide +kernel

theorem box_00_chunk_001 :
    boxCellChunk (profileBox 0) 25 25 =
      ⟨0,
        3840710708025486723996669474761096444325149029965008297229550644448697775097477137894204765775598697518822593076198259126527832863349841⟩ := by
  decide +kernel

theorem box_00_chunk_002 :
    boxCellChunk (profileBox 0) 50 25 =
      ⟨0,
        24321129560637117956142024137077838709605634287904450663581892557038030343330908932370189247562149729577⟩ := by
  decide +kernel

theorem box_00_chunk_003 :
    boxCellChunk (profileBox 0) 75 25 =
      ⟨0,
        6137753664436806662737902078160255873512652070124005342539716814915489340⟩ := by
  decide +kernel

theorem box_00_chunk_004 :
    boxCellChunk (profileBox 0) 100 25 =
      ⟨0,
        96801043157363830427150499613519963665893795458⟩ := by
  decide +kernel

theorem box_00_chunk_005 :
    boxCellChunk (profileBox 0) 125 25 =
      ⟨0,
        38030428302243442921635239⟩ := by
  decide +kernel

theorem box_00_chunk_006 :
    boxCellChunk (profileBox 0) 150 25 =
      ⟨0,
        97940120⟩ := by
  decide +kernel

theorem box_00_chunk_007 :
    boxCellChunk (profileBox 0) 175 25 =
      ⟨0,
        25⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
