/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_00_chunk_008 :
    boxCellChunk (profileBox 0) 200 25 =
      ⟨0,
        25⟩ := by
  decide +kernel

theorem box_00_chunk_009 :
    boxCellChunk (profileBox 0) 225 25 =
      ⟨0,
        25⟩ := by
  decide +kernel

theorem box_00_chunk_010 :
    boxCellChunk (profileBox 0) 250 25 =
      ⟨0,
        25⟩ := by
  decide +kernel

theorem box_00_chunk_011 :
    boxCellChunk (profileBox 0) 275 25 =
      ⟨0,
        131930033492729423157⟩ := by
  decide +kernel

theorem box_00_chunk_012 :
    boxCellChunk (profileBox 0) 300 25 =
      ⟨0,
        4126538186535251908297317392444216032856157098190315681370⟩ := by
  decide +kernel

theorem box_00_chunk_013 :
    boxCellChunk (profileBox 0) 325 25 =
      ⟨0,
        221190855450056230741865801958689111562337405801179789500984074041784125057853171351663787249017991790624915⟩ := by
  decide +kernel

theorem box_00_chunk_014 :
    boxCellChunk (profileBox 0) 350 25 =
      ⟨0,
        5905830642259471084185573487380013265634450258356346363281148593707834757168418789737231275759284100166766149723334393285623165853684750538349312001223⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
