/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box03
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box03.Shard00
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box03.Shard01

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix03 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box03.chunks.take 9

private theorem chunks03 : computedChunks (profileBox 3) 9 = prefix03 := by
  change [
    boxCellChunk (profileBox 3) 0 25,
    boxCellChunk (profileBox 3) 25 25,
    boxCellChunk (profileBox 3) 50 25,
    boxCellChunk (profileBox 3) 75 25,
    boxCellChunk (profileBox 3) 100 25,
    boxCellChunk (profileBox 3) 125 25,
    boxCellChunk (profileBox 3) 150 25,
    boxCellChunk (profileBox 3) 175 25,
    boxCellChunk (profileBox 3) 200 25] = prefix03
  rw [Internal.box_03_chunk_000,
    Internal.box_03_chunk_001,
    Internal.box_03_chunk_002,
    Internal.box_03_chunk_003,
    Internal.box_03_chunk_004,
    Internal.box_03_chunk_005,
    Internal.box_03_chunk_006,
    Internal.box_03_chunk_007,
    Internal.box_03_chunk_008]
  rfl

private theorem budget03 :
    Interval.upperLTCheck (boundFrom (profileBox 3) 9 prefix03)
      (profileBox 3).target = true := by decide +kernel

theorem box03_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 3).profileLeft : ℝ)
      ((profileBox 3).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 3) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 3) profile frequency) <
      ((profileBox 3).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 9
    (by decide) (by decide +kernel) prefix03 chunks03
    (Interval.upperLTCheck_sound budget03) hp

end CertifiedJL.SparseUpperContour.ShortTail
