/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box08
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box08.Shard00

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix08 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box08.chunks.take 4

private theorem chunks08 : computedChunks (profileBox 8) 4 = prefix08 := by
  change [
    boxCellChunk (profileBox 8) 0 25,
    boxCellChunk (profileBox 8) 25 25,
    boxCellChunk (profileBox 8) 50 25,
    boxCellChunk (profileBox 8) 75 25] = prefix08
  rw [Internal.box_08_chunk_000,
    Internal.box_08_chunk_001,
    Internal.box_08_chunk_002,
    Internal.box_08_chunk_003]
  rfl

private theorem budget08 :
    Interval.upperLTCheck (boundFrom (profileBox 8) 4 prefix08)
      (profileBox 8).target = true := by decide +kernel

theorem box08_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 8).profileLeft : ℝ)
      ((profileBox 8).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 8) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 8) profile frequency) <
      ((profileBox 8).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 4
    (by decide) (by decide +kernel) prefix08 chunks08
    (Interval.upperLTCheck_sound budget08) hp

end CertifiedJL.SparseUpperContour.ShortTail
