/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box02
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box02.Shard00
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box02.Shard01

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix02 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box02.chunks.take 10

private theorem chunks02 : computedChunks (profileBox 2) 10 = prefix02 := by
  change [
    boxCellChunk (profileBox 2) 0 25,
    boxCellChunk (profileBox 2) 25 25,
    boxCellChunk (profileBox 2) 50 25,
    boxCellChunk (profileBox 2) 75 25,
    boxCellChunk (profileBox 2) 100 25,
    boxCellChunk (profileBox 2) 125 25,
    boxCellChunk (profileBox 2) 150 25,
    boxCellChunk (profileBox 2) 175 25,
    boxCellChunk (profileBox 2) 200 25,
    boxCellChunk (profileBox 2) 225 25] = prefix02
  rw [Internal.box_02_chunk_000,
    Internal.box_02_chunk_001,
    Internal.box_02_chunk_002,
    Internal.box_02_chunk_003,
    Internal.box_02_chunk_004,
    Internal.box_02_chunk_005,
    Internal.box_02_chunk_006,
    Internal.box_02_chunk_007,
    Internal.box_02_chunk_008,
    Internal.box_02_chunk_009]
  rfl

private theorem budget02 :
    Interval.upperLTCheck (boundFrom (profileBox 2) 10 prefix02)
      (profileBox 2).target = true := by decide +kernel

theorem box02_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 2).profileLeft : ℝ)
      ((profileBox 2).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 2) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 2) profile frequency) <
      ((profileBox 2).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 10
    (by decide) (by decide +kernel) prefix02 chunks02
    (Interval.upperLTCheck_sound budget02) hp

end CertifiedJL.SparseUpperContour.ShortTail
