/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box01
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box01.Shard00
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box01.Shard01

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix01 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box01.chunks.take 12

private theorem chunks01 : computedChunks (profileBox 1) 12 = prefix01 := by
  change [
    boxCellChunk (profileBox 1) 0 25,
    boxCellChunk (profileBox 1) 25 25,
    boxCellChunk (profileBox 1) 50 25,
    boxCellChunk (profileBox 1) 75 25,
    boxCellChunk (profileBox 1) 100 25,
    boxCellChunk (profileBox 1) 125 25,
    boxCellChunk (profileBox 1) 150 25,
    boxCellChunk (profileBox 1) 175 25,
    boxCellChunk (profileBox 1) 200 25,
    boxCellChunk (profileBox 1) 225 25,
    boxCellChunk (profileBox 1) 250 25,
    boxCellChunk (profileBox 1) 275 25] = prefix01
  rw [Internal.box_01_chunk_000,
    Internal.box_01_chunk_001,
    Internal.box_01_chunk_002,
    Internal.box_01_chunk_003,
    Internal.box_01_chunk_004,
    Internal.box_01_chunk_005,
    Internal.box_01_chunk_006,
    Internal.box_01_chunk_007,
    Internal.box_01_chunk_008,
    Internal.box_01_chunk_009,
    Internal.box_01_chunk_010,
    Internal.box_01_chunk_011]
  rfl

private theorem budget01 :
    Interval.upperLTCheck (boundFrom (profileBox 1) 12 prefix01)
      (profileBox 1).target = true := by decide +kernel

theorem box01_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 1).profileLeft : ℝ)
      ((profileBox 1).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 1) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 1) profile frequency) <
      ((profileBox 1).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 12
    (by decide) (by decide +kernel) prefix01 chunks01
    (Interval.upperLTCheck_sound budget01) hp

end CertifiedJL.SparseUpperContour.ShortTail
