/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box07
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box07.Shard00

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix07 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box07.chunks.take 5

private theorem chunks07 : computedChunks (profileBox 7) 5 = prefix07 := by
  change [
    boxCellChunk (profileBox 7) 0 25,
    boxCellChunk (profileBox 7) 25 25,
    boxCellChunk (profileBox 7) 50 25,
    boxCellChunk (profileBox 7) 75 25,
    boxCellChunk (profileBox 7) 100 25] = prefix07
  rw [Internal.box_07_chunk_000,
    Internal.box_07_chunk_001,
    Internal.box_07_chunk_002,
    Internal.box_07_chunk_003,
    Internal.box_07_chunk_004]
  rfl

private theorem budget07 :
    Interval.upperLTCheck (boundFrom (profileBox 7) 5 prefix07)
      (profileBox 7).target = true := by decide +kernel

theorem box07_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 7).profileLeft : ℝ)
      ((profileBox 7).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 7) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 7) profile frequency) <
      ((profileBox 7).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 5
    (by decide) (by decide +kernel) prefix07 chunks07
    (Interval.upperLTCheck_sound budget07) hp

end CertifiedJL.SparseUpperContour.ShortTail
