/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box00
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box00.Shard00
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box00.Shard01

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix00 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box00.chunks.take 15

private theorem chunks00 : computedChunks (profileBox 0) 15 = prefix00 := by
  change [
    boxCellChunk (profileBox 0) 0 25,
    boxCellChunk (profileBox 0) 25 25,
    boxCellChunk (profileBox 0) 50 25,
    boxCellChunk (profileBox 0) 75 25,
    boxCellChunk (profileBox 0) 100 25,
    boxCellChunk (profileBox 0) 125 25,
    boxCellChunk (profileBox 0) 150 25,
    boxCellChunk (profileBox 0) 175 25,
    boxCellChunk (profileBox 0) 200 25,
    boxCellChunk (profileBox 0) 225 25,
    boxCellChunk (profileBox 0) 250 25,
    boxCellChunk (profileBox 0) 275 25,
    boxCellChunk (profileBox 0) 300 25,
    boxCellChunk (profileBox 0) 325 25,
    boxCellChunk (profileBox 0) 350 25] = prefix00
  rw [Internal.box_00_chunk_000,
    Internal.box_00_chunk_001,
    Internal.box_00_chunk_002,
    Internal.box_00_chunk_003,
    Internal.box_00_chunk_004,
    Internal.box_00_chunk_005,
    Internal.box_00_chunk_006,
    Internal.box_00_chunk_007,
    Internal.box_00_chunk_008,
    Internal.box_00_chunk_009,
    Internal.box_00_chunk_010,
    Internal.box_00_chunk_011,
    Internal.box_00_chunk_012,
    Internal.box_00_chunk_013,
    Internal.box_00_chunk_014]
  rfl

private theorem budget00 :
    Interval.upperLTCheck (boundFrom (profileBox 0) 15 prefix00)
      (profileBox 0).target = true := by decide +kernel

theorem box00_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 0).profileLeft : ℝ)
      ((profileBox 0).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 0) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 0) profile frequency) <
      ((profileBox 0).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 15
    (by decide) (by decide +kernel) prefix00 chunks00
    (Interval.upperLTCheck_sound budget00) hp

end CertifiedJL.SparseUpperContour.ShortTail
