/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box05
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box05.Shard00

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix05 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box05.chunks.take 7

private theorem chunks05 : computedChunks (profileBox 5) 7 = prefix05 := by
  change [
    boxCellChunk (profileBox 5) 0 25,
    boxCellChunk (profileBox 5) 25 25,
    boxCellChunk (profileBox 5) 50 25,
    boxCellChunk (profileBox 5) 75 25,
    boxCellChunk (profileBox 5) 100 25,
    boxCellChunk (profileBox 5) 125 25,
    boxCellChunk (profileBox 5) 150 25] = prefix05
  rw [Internal.box_05_chunk_000,
    Internal.box_05_chunk_001,
    Internal.box_05_chunk_002,
    Internal.box_05_chunk_003,
    Internal.box_05_chunk_004,
    Internal.box_05_chunk_005,
    Internal.box_05_chunk_006]
  rfl

private theorem budget05 :
    Interval.upperLTCheck (boundFrom (profileBox 5) 7 prefix05)
      (profileBox 5).target = true := by decide +kernel

theorem box05_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 5).profileLeft : ℝ)
      ((profileBox 5).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 5) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 5) profile frequency) <
      ((profileBox 5).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 7
    (by decide) (by decide +kernel) prefix05 chunks05
    (Interval.upperLTCheck_sound budget05) hp

end CertifiedJL.SparseUpperContour.ShortTail
