/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box06
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box06.Shard00

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix06 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box06.chunks.take 6

private theorem chunks06 : computedChunks (profileBox 6) 6 = prefix06 := by
  change [
    boxCellChunk (profileBox 6) 0 25,
    boxCellChunk (profileBox 6) 25 25,
    boxCellChunk (profileBox 6) 50 25,
    boxCellChunk (profileBox 6) 75 25,
    boxCellChunk (profileBox 6) 100 25,
    boxCellChunk (profileBox 6) 125 25] = prefix06
  rw [Internal.box_06_chunk_000,
    Internal.box_06_chunk_001,
    Internal.box_06_chunk_002,
    Internal.box_06_chunk_003,
    Internal.box_06_chunk_004,
    Internal.box_06_chunk_005]
  rfl

private theorem budget06 :
    Interval.upperLTCheck (boundFrom (profileBox 6) 6 prefix06)
      (profileBox 6).target = true := by decide +kernel

theorem box06_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 6).profileLeft : ℝ)
      ((profileBox 6).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 6) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 6) profile frequency) <
      ((profileBox 6).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 6
    (by decide) (by decide +kernel) prefix06 chunks06
    (Interval.upperLTCheck_sound budget06) hp

end CertifiedJL.SparseUpperContour.ShortTail
