/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box09
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box09.Shard00

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix09 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box09.chunks.take 3

private theorem chunks09 : computedChunks (profileBox 9) 3 = prefix09 := by
  change [
    boxCellChunk (profileBox 9) 0 25,
    boxCellChunk (profileBox 9) 25 25,
    boxCellChunk (profileBox 9) 50 25] = prefix09
  rw [Internal.box_09_chunk_000,
    Internal.box_09_chunk_001,
    Internal.box_09_chunk_002]
  rfl

private theorem budget09 :
    Interval.upperLTCheck (boundFrom (profileBox 9) 3 prefix09)
      (profileBox 9).target = true := by decide +kernel

theorem box09_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 9).profileLeft : ℝ)
      ((profileBox 9).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 9) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 9) profile frequency) <
      ((profileBox 9).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 3
    (by decide) (by decide +kernel) prefix09 chunks09
    (Interval.upperLTCheck_sound budget09) hp

end CertifiedJL.SparseUpperContour.ShortTail
