/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Soundness
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Data.Box04
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Shards.Box04.Shard00

namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix04 : List (Interval contourPrecision) :=
  SparseUpperContourData.Box04.chunks.take 8

private theorem chunks04 : computedChunks (profileBox 4) 8 = prefix04 := by
  change [
    boxCellChunk (profileBox 4) 0 25,
    boxCellChunk (profileBox 4) 25 25,
    boxCellChunk (profileBox 4) 50 25,
    boxCellChunk (profileBox 4) 75 25,
    boxCellChunk (profileBox 4) 100 25,
    boxCellChunk (profileBox 4) 125 25,
    boxCellChunk (profileBox 4) 150 25,
    boxCellChunk (profileBox 4) 175 25] = prefix04
  rw [Internal.box_04_chunk_000,
    Internal.box_04_chunk_001,
    Internal.box_04_chunk_002,
    Internal.box_04_chunk_003,
    Internal.box_04_chunk_004,
    Internal.box_04_chunk_005,
    Internal.box_04_chunk_006,
    Internal.box_04_chunk_007]
  rfl

private theorem budget04 :
    Interval.upperLTCheck (boundFrom (profileBox 4) 8 prefix04)
      (profileBox 4).target = true := by decide +kernel

theorem box04_endpoint {profile : ℝ}
    (hp : profile ∈ Set.Icc ((profileBox 4).profileLeft : ℝ)
      ((profileBox 4).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox 4) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox 4) profile frequency) <
      ((profileBox 4).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) 8
    (by decide) (by decide +kernel) prefix04 chunks04
    (Interval.upperLTCheck_sound budget04) hp

end CertifiedJL.SparseUpperContour.ShortTail
