/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.Soundness.HighProfile
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box00
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box01
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box02
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box03
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box04
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box05
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box06
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box07
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box08
import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Replay.Box09

namespace CertifiedJL.SparseUpperContour.ShortTail

theorem all_endpoints {box : ProfileBox} (hbox : box ∈ profileBoxes)
    {profile : ℝ} (hp : profile ∈ Set.Icc (box.profileLeft : ℝ) (box.profileRight : ℝ)) :
    boxActualPrefactorValue box *
      (∫ frequency : ℝ in Set.Ioi 0, actualBoxQuadratureIntegrand box profile frequency) <
      (box.target : ℝ) := by
  simp only [profileBoxes, List.mem_cons, List.not_mem_nil, or_false] at hbox
  rcases hbox with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact box00_endpoint hp
  · exact box01_endpoint hp
  · exact box02_endpoint hp
  · exact box03_endpoint hp
  · exact box04_endpoint hp
  · exact box05_endpoint hp
  · exact box06_endpoint hp
  · exact box07_endpoint hp
  · exact box08_endpoint hp
  · exact box09_endpoint hp

end CertifiedJL.SparseUpperContour.ShortTail
