/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Central.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Central

private def dominationLeaf00BernsteinNumerators : List ℤ :=
  [
    (1482000939170135269390616475789159885519485770478910715355362896478734986416598841630 : ℤ), (67253920466749945422493081479278709776667105325502779853116647482746555039671171536652 : ℤ), (128949391472950049421160026868121857698623292802359654250406434798937196945665209934556 : ℤ),
    (186249564806101639533704743380464402269693160343663169123799584426639708708085848644852 : ℤ), (238807317558769407378791614307877815045209359245708122469442253574608352086498707483780 : ℤ), (286245024353377403294042212261872647394104332129151894258912867074701887687140458870945 : ℤ),
    (328152191054700944796576528913050976080891174379288393558371528420885799485266685774189 : ℤ), (364082944220661807818663552279561748443598449678239388200603707321700444222706267682027 : ℤ), (393553369343973587503812715977547447524155066481161469054456082804582059018351378437079 : ℤ),
    (416038690670390821259166045711067242256649052980596364087044127899337415609690534000000 : ℤ), (430970285104436370073559931294193757293907938144924242308677344886091440890000000000000 : ℤ), (437732522430330888064652926682266996076835161587698640269619300996380000000000000000000 : ℤ),
    (435659423784237272295322174338599830920091527484169327599566586000000000000000000000000 : ℤ), (424031130013670112427894113330780414965167337328693252004000000000000000000000000000000 : ℤ), (402070171250810705541786035028463662161303541809485750000000000000000000000000000000000 : ℤ),
    (368937528708314509252992612571657263253853802500000000000000000000000000000000000000000 : ℤ), (323728479378799286621657432602847810714000000000000000000000000000000000000000000000000 : ℤ), (265468213982354901949523369694404000000000000000000000000000000000000000000000000000000 : ℤ),
    (193107218159912928040649844000000000000000000000000000000000000000000000000000000000000 : ℤ), (105516406553945986872000000000000000000000000000000000000000000000000000000000000000000 : ℤ), (1481999051520000000000000000000000000000000000000000000000000000000000000000000000000 : ℤ)
  ]

private abbrev dominationLeaf00BernsteinDenominator : ℤ := 14820000000000000000000000000000000000000000000000000000000000000000000000000000000000000

private def dominationLeaf00Bernstein : List ℚ :=
  dominationLeaf00BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / dominationLeaf00BernsteinDenominator

theorem dominationLeaf00BernsteinScaleCheck :
    integerScaleBlockCheck dominationLeaf00Bernstein dominationLeaf00BernsteinNumerators
      dominationLeaf00BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem dominationLeaf00BernsteinScale : ∀ k ≤ degree,
    dominationLeaf00Bernstein.getD k 0 * dominationLeaf00BernsteinDenominator =
      dominationLeaf00BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound dominationLeaf00BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem dominationLeaf00IdentityCheck :
    integerBernsteinIdentityBlockCheck dominationPowerNumerators powerDenominator
      (1859733 : ℤ) (140267 : ℤ)
      (2000000 : ℤ) degree
      dominationLeaf00BernsteinNumerators dominationLeaf00BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem dominationLeaf00NonnegativeCheck :
    nonnegativeBlockCheck dominationLeaf00Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem dominationLeaf00Identity :
    affinePullbackQ (powerPolynomialQ (subtractConstant power 1))
        (1859733 / 2000000 : ℚ) (1 : ℚ) =
      bernsteinPolynomialQ degree dominationLeaf00Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, subtractConstant])
    (by simp [degree, dominationLeaf00Bernstein, dominationLeaf00BernsteinNumerators])
    (by simp [degree, dominationPowerNumerators]) dominationPowerIntegerScale dominationLeaf00BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    dominationLeaf00IdentityCheck

theorem dominationLeaf00Nonneg {y : ℝ}
    (hlo : (((1859733 / 2000000 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((1 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (subtractConstant power 1) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi dominationLeaf00Identity
  intro k hk
  exact nonnegativeBlockCheck_sound dominationLeaf00NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem dominationLeaf00Tree :
    NonnegativeTree (rationalPowerValue (subtractConstant power 1))
      (1859733 / 2000000 : ℚ) (1 : ℚ) :=
  .leaf (fun _y hlo hhi => dominationLeaf00Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Central
