/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Central.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Central

private def globalLeaf07BernsteinNumerators : List ℤ :=
  [
    (111638902023334920 : ℤ), (141512964487073868 : ℤ), (176825413974049932 : ℤ),
    (217791032036829680 : ℤ), (264403805402847032 : ℤ), (316390927052500625 : ℤ),
    (373183809504525565 : ℤ), (433916149709673514 : ℤ), (497458827533195728 : ℤ),
    (562499017214923230 : ℤ), (627665290348852230 : ℤ), (691690379317507320 : ℤ),
    (753587055222584524 : ℤ), (812788343019981991 : ℤ), (869168794414433227 : ℤ),
    (922816139887023590 : ℤ), (973359318376402568 : ℤ), (1018576180935777152 : ℤ),
    (1051898169830546064 : ℤ), (1058295587474674848 : ℤ), (1007860775935503360 : ℤ)
  ]

private abbrev globalLeaf07BernsteinDenominator : ℤ := 1007760000000000000

private def globalLeaf07Bernstein : List ℚ :=
  globalLeaf07BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf07BernsteinDenominator

theorem globalLeaf07BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf07Bernstein globalLeaf07BernsteinNumerators
      globalLeaf07BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf07BernsteinScale : ∀ k ≤ degree,
    globalLeaf07Bernstein.getD k 0 * globalLeaf07BernsteinDenominator =
      globalLeaf07BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf07BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf07IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (1 : ℤ) (1 : ℤ)
      (2 : ℤ) degree
      globalLeaf07BernsteinNumerators globalLeaf07BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf07NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf07Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf07Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (1 / 2 : ℚ) (1 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf07Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf07Bernstein, globalLeaf07BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf07BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf07IdentityCheck

theorem globalLeaf07Nonneg {y : ℝ}
    (hlo : (((1 / 2 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((1 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf07Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf07NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf07Tree :
    NonnegativeTree (rationalPowerValue (power))
      (1 / 2 : ℚ) (1 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf07Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Central
