/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Central.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Central

private def globalLeaf05BernsteinNumerators : List ℤ :=
  [
    (1077016967842694313630 : ℤ), (1052075995397243302512 : ℤ), (1013721911935139606628 : ℤ),
    (962163969344553815060 : ℤ), (898240121014761659108 : ℤ), (823516180463929043975 : ℤ),
    (740386324876240443505 : ℤ), (652173917019614936791 : ℤ), (563231578407164085847 : ℤ),
    (479039415074433208590 : ℤ), (406300275584631405420 : ℤ), (353030909395439830200 : ℤ),
    (328647893002030331536 : ℤ), (344047201711409626144 : ℤ), (411676326817102654528 : ℤ),
    (545597871551520344960 : ℤ), (761543604617031322112 : ℤ), (1076958007349425230848 : ℤ),
    (1511030419548359264256 : ℤ), (2084714969496201449472 : ℤ), (2820737565328396247040 : ℤ)
  ]

private abbrev globalLeaf05BernsteinDenominator : ℤ := 4226851799040000000000000

private def globalLeaf05Bernstein : List ℚ :=
  globalLeaf05BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf05BernsteinDenominator

theorem globalLeaf05BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf05Bernstein globalLeaf05BernsteinNumerators
      globalLeaf05BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05BernsteinScale : ∀ k ≤ degree,
    globalLeaf05Bernstein.getD k 0 * globalLeaf05BernsteinDenominator =
      globalLeaf05BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf05BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf05IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (1 : ℤ) (1 : ℤ)
      (8 : ℤ) degree
      globalLeaf05BernsteinNumerators globalLeaf05BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf05Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (1 / 8 : ℚ) (1 / 4 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf05Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf05Bernstein, globalLeaf05BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf05BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf05IdentityCheck

theorem globalLeaf05Nonneg {y : ℝ}
    (hlo : (((1 / 8 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((1 / 4 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf05Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf05NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf05Tree :
    NonnegativeTree (rationalPowerValue (power))
      (1 / 8 : ℚ) (1 / 4 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf05Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Central
