/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Central.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Central

private def globalLeaf02BernsteinNumerators : List ℤ :=
  [
    (2820737565328396247040 : ℤ), (2084714969496201449472 : ℤ), (1511030419548359264256 : ℤ),
    (1076958007349425230848 : ℤ), (761543604617031322112 : ℤ), (545597871551520344960 : ℤ),
    (411676326817102654528 : ℤ), (344047201711409626144 : ℤ), (328647893002030331536 : ℤ),
    (353030909395439830200 : ℤ), (406300275584631405420 : ℤ), (479039415074433208590 : ℤ),
    (563231578407164085847 : ℤ), (652173917019614936791 : ℤ), (740386324876240443505 : ℤ),
    (823516180463929043975 : ℤ), (898240121014761659108 : ℤ), (962163969344553815060 : ℤ),
    (1013721911935139606628 : ℤ), (1052075995397243302512 : ℤ), (1077016967842694313630 : ℤ)
  ]

private abbrev globalLeaf02BernsteinDenominator : ℤ := 4226851799040000000000000

private def globalLeaf02Bernstein : List ℚ :=
  globalLeaf02BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf02BernsteinDenominator

theorem globalLeaf02BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf02Bernstein globalLeaf02BernsteinNumerators
      globalLeaf02BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf02BernsteinScale : ∀ k ≤ degree,
    globalLeaf02Bernstein.getD k 0 * globalLeaf02BernsteinDenominator =
      globalLeaf02BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf02BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf02IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-2 : ℤ) (1 : ℤ)
      (8 : ℤ) degree
      globalLeaf02BernsteinNumerators globalLeaf02BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf02NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf02Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf02Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-1 / 4 : ℚ) (-1 / 8 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf02Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf02Bernstein, globalLeaf02BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf02BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf02IdentityCheck

theorem globalLeaf02Nonneg {y : ℝ}
    (hlo : (((-1 / 4 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((-1 / 8 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf02Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf02NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf02Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-1 / 4 : ℚ) (-1 / 8 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf02Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Central
