/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Central.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Central

private def globalLeaf01BernsteinNumerators : List ℤ :=
  [
    (114318235671894958080 : ℤ), (99022715690460616704 : ℤ), (85119422786974977024 : ℤ),
    (72580864922709518336 : ℤ), (61365419190127230464 : ℤ), (51418803778383498080 : ℤ),
    (42675822134143375216 : ℤ), (35062299002506978384 : ℤ), (28497127003152569392 : ℤ),
    (22894345657467063816 : ℤ), (18165181280352163620 : ℤ), (14219984961197317734 : ℤ),
    (10970016179384206759 : ℤ), (8329030742226500215 : ℤ), (6214643116306877785 : ℤ),
    (4549444365712358255 : ℤ), (3261867424607876708 : ℤ), (2286801014652673844 : ℤ),
    (1565961946336568820 : ℤ), (1048042665281441856 : ℤ), (688656632160252990 : ℤ)
  ]

private abbrev globalLeaf01BernsteinDenominator : ℤ := 1031946240000000000000

private def globalLeaf01Bernstein : List ℚ :=
  globalLeaf01BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf01BernsteinDenominator

theorem globalLeaf01BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf01Bernstein globalLeaf01BernsteinNumerators
      globalLeaf01BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf01BernsteinScale : ∀ k ≤ degree,
    globalLeaf01Bernstein.getD k 0 * globalLeaf01BernsteinDenominator =
      globalLeaf01BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf01BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf01IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-2 : ℤ) (1 : ℤ)
      (4 : ℤ) degree
      globalLeaf01BernsteinNumerators globalLeaf01BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf01NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf01Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf01Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-1 / 2 : ℚ) (-1 / 4 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf01Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf01Bernstein, globalLeaf01BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf01BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf01IdentityCheck

theorem globalLeaf01Nonneg {y : ℝ}
    (hlo : (((-1 / 2 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((-1 / 4 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf01Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf01NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf01Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-1 / 2 : ℚ) (-1 / 4 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf01Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Central
