/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Central.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Central

private def globalLeaf03BernsteinNumerators : List ℤ :=
  [
    (1077016967842694313630 : ℤ), (1101957940288145324748 : ℤ), (1113485801716943651100 : ℤ),
    (1111391300240918703604 : ℤ), (1096093885473005035396 : ℤ), (1068542549899457310145 : ℤ),
    (1030118015161408633421 : ℤ), (982537289774527968299 : ℤ), (927761584207442276759 : ℤ),
    (867908519514521514144 : ℤ), (805169507490878669280 : ℤ), (741733114265666836992 : ℤ),
    (679715146109819546112 : ℤ), (621096116792191951872 : ℤ), (567666670902435167232 : ℤ),
    (520981448034442936320 : ℤ), (482321779484020310016 : ℤ), (452667513073160945664 : ℤ),
    (432678163799907237888 : ℤ), (422683489163280384000 : ℤ), (422683489163280384000 : ℤ)
  ]

private abbrev globalLeaf03BernsteinDenominator : ℤ := 4226851799040000000000000

private def globalLeaf03Bernstein : List ℚ :=
  globalLeaf03BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf03BernsteinDenominator

theorem globalLeaf03BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf03Bernstein globalLeaf03BernsteinNumerators
      globalLeaf03BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf03BernsteinScale : ∀ k ≤ degree,
    globalLeaf03Bernstein.getD k 0 * globalLeaf03BernsteinDenominator =
      globalLeaf03BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf03BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf03IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-1 : ℤ) (1 : ℤ)
      (8 : ℤ) degree
      globalLeaf03BernsteinNumerators globalLeaf03BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf03NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf03Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf03Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-1 / 8 : ℚ) (0 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf03Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf03Bernstein, globalLeaf03BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf03BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf03IdentityCheck

theorem globalLeaf03Nonneg {y : ℝ}
    (hlo : (((-1 / 8 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((0 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf03Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf03NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf03Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-1 / 8 : ℚ) (0 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf03Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Central
