/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Data.Cap24Central.Data

open CertifiedJL.TrigonometricBernstein

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Central

theorem powerIntegerScaleCheck :
    integerScaleBlockCheck power powerNumerators powerDenominator
      0 (degree + 1) = true := by
  decide +kernel

theorem powerIntegerScale : ∀ k ≤ degree,
    power.getD k 0 * powerDenominator = powerNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound powerIntegerScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

theorem dominationPowerIntegerScaleCheck :
    integerScaleBlockCheck (subtractConstant power 1) dominationPowerNumerators
      powerDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem dominationPowerIntegerScale : ∀ k ≤ degree,
    (subtractConstant power 1).getD k 0 * powerDenominator =
      dominationPowerNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound dominationPowerIntegerScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Central
