/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_01_chunk_000 :
    boxCellChunk (profileBox 1) 0 25 =
      ⟨0,
        792299427989421752406980513649493377728144080260790251631814304696123901403892835700798416929356372099058139438548682651203289684805781854837626893155597⟩ := by
  decide +kernel

theorem box_01_chunk_001 :
    boxCellChunk (profileBox 1) 25 25 =
      ⟨0,
        4096093338046708935431950274267175783528441854735596262077563980907385652562492425922296731401187097976574733567195941850392385484017689⟩ := by
  decide +kernel

theorem box_01_chunk_002 :
    boxCellChunk (profileBox 1) 50 25 =
      ⟨0,
        28303860634607218478720648749190321285502283628505641041684230629343894178643585590465278853321331156404⟩ := by
  decide +kernel

theorem box_01_chunk_003 :
    boxCellChunk (profileBox 1) 75 25 =
      ⟨0,
        8361055292893833959420378895663844652685607193008561799312467169408333316⟩ := by
  decide +kernel

theorem box_01_chunk_004 :
    boxCellChunk (profileBox 1) 100 25 =
      ⟨0,
        249672598486710670631197153050385579272843052342⟩ := by
  decide +kernel

theorem box_01_chunk_005 :
    boxCellChunk (profileBox 1) 125 25 =
      ⟨0,
        662407507545436489525360147⟩ := by
  decide +kernel

theorem box_01_chunk_006 :
    boxCellChunk (profileBox 1) 150 25 =
      ⟨0,
        210799688375⟩ := by
  decide +kernel

theorem box_01_chunk_007 :
    boxCellChunk (profileBox 1) 175 25 =
      ⟨0,
        216⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
