/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_01_chunk_008 :
    boxCellChunk (profileBox 1) 200 25 =
      ⟨0,
        813342111233⟩ := by
  decide +kernel

theorem box_01_chunk_009 :
    boxCellChunk (profileBox 1) 225 25 =
      ⟨0,
        385940861966428486796425240357460526618⟩ := by
  decide +kernel

theorem box_01_chunk_010 :
    boxCellChunk (profileBox 1) 250 25 =
      ⟨0,
        108285078493086265252971960716654343597410623060796158401324890906458739135072958192⟩ := by
  decide +kernel

theorem box_01_chunk_011 :
    boxCellChunk (profileBox 1) 275 25 =
      ⟨0,
        902240289353159190216753158622619934515102129117126439923491068122197162592477898719209450179045725438236799319663505200099539616691638833358940⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
