/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_05_chunk_000 :
    boxCellChunk (profileBox 5) 0 25 =
      ⟨0,
        499569882834473550879010457899241420811954235069586114801865317171041418507436877839062521711251334722043069054019852394049607245206467419016602249292554⟩ := by
  decide +kernel

theorem box_05_chunk_001 :
    boxCellChunk (profileBox 5) 25 25 =
      ⟨0,
        7228962780804536426846260181953395963803720060079445294262923552522613307116442788061971131602596128369979604498026928421280066752472522⟩ := by
  decide +kernel

theorem box_05_chunk_002 :
    boxCellChunk (profileBox 5) 50 25 =
      ⟨0,
        126522952657170697908947273065291799489745355493570321366332861475937356654186797189277618844660521640555⟩ := by
  decide +kernel

theorem box_05_chunk_003 :
    boxCellChunk (profileBox 5) 75 25 =
      ⟨0,
        409576879574924393809426870058670811246872893463555739749724810294258513408⟩ := by
  decide +kernel

theorem box_05_chunk_004 :
    boxCellChunk (profileBox 5) 100 25 =
      ⟨0,
        57881921424472031120421281080487742974513766622027284⟩ := by
  decide +kernel

theorem box_05_chunk_005 :
    boxCellChunk (profileBox 5) 125 25 =
      ⟨0,
        169618967337547304990942442665336983610963332072160⟩ := by
  decide +kernel

theorem box_05_chunk_006 :
    boxCellChunk (profileBox 5) 150 25 =
      ⟨0,
        53936223130824091078532819597470980908689532752295383485480393064525638237790798643595⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
