/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Data.Cap34Central.Data

open CertifiedJL.TrigonometricBernstein

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap34Central

set_option maxHeartbeats 40000000 in
-- Kernel reduction checks that the frozen Fourier data converts to this exact power list.
set_option maxRecDepth 1000000 in
theorem fourierPowerCheck :
    chebyshevCombinationPower fourier = power := by
  decide +kernel

theorem fourierTailNonpositiveCheck :
    nonpositiveBlockCheck fourier 3
      (degree + 1 - 3) = true := by
  decide +kernel

theorem fourierContract :
    CentralFourierContract fourier degree phiOneBound phiTwoBound expectationBound := by
  refine ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    by decide +kernel, ?_, by decide +kernel⟩
  intro j hjStart hjLength
  apply nonpositiveBlockCheck_sound fourierTailNonpositiveCheck j hjStart
  have hlength : fourier.length = degree + 1 := by decide +kernel
  rw [hlength] at hjLength
  have hdegree : 3 ≤ degree + 1 := by decide +kernel
  omega

end CertifiedJL.TernaryLInfTwoDecimal.Cap34Central
