/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_08_chunk_000 :
    boxCellChunk (profileBox 8) 0 25 =
      ⟨0,
        122661807514806569024349629402584902563190275195366325045418942140190738052872277283785963223778732777410742882412971217567208049325544733131866477285835⟩ := by
  decide +kernel

theorem box_08_chunk_001 :
    boxCellChunk (profileBox 8) 25 25 =
      ⟨0,
        403163750387888100427116966066173278220448196639448579437609983244459620197304240902893985973787624965915216204296638298322374999106885968⟩ := by
  decide +kernel

theorem box_08_chunk_002 :
    boxCellChunk (profileBox 8) 50 25 =
      ⟨0,
        14736536911218545133872113087800462670819989135416188469550709328900734556316961860152667160687899643055949266⟩ := by
  decide +kernel

theorem box_08_chunk_003 :
    boxCellChunk (profileBox 8) 75 25 =
      ⟨0,
        3134912130601753634973738515736914580320448410122074232594334632600834409106102996976219030805327872⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
