/-
Copyright (c) 2026 Anonymous Author. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anonymous Author
-/

import CertifiedJL.Certificates.Families.L2Lower.Shared.Spec

/-! # Assumption-backed providers for threshold-relative lower-tail replay -/

namespace CertifiedJLFast.Assumptions

axiom sparse_l2_threshold_dominant_direct_cover128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantDirectCover128
axiom sparse_l2_threshold_dominant_capped_fourier_cover128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantCappedFourierCover128
axiom sparse_l2_threshold_dominant_singleton_fourier_cover128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantSingletonFourierCover128
axiom sparse_l2_threshold_dominant_retained_coarse128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantRetainedCoarse128
axiom sparse_l2_threshold_dominant_retained_chord128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantRetainedChord128
axiom sparse_l2_threshold_dominant_final_ratio128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantFinalRatio128
axiom sparse_l2_threshold_near_coarse_cover128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearCoarseCover128
axiom sparse_l2_threshold_near_endpoints128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearEndpoints128
axiom sparse_l2_threshold_near_curvature128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearCurvature128
axiom sparse_l2_threshold_diffuse_low_scalar128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseLowScalar128
axiom sparse_l2_threshold_diffuse_low_modular_tail128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseLowModularTail128
axiom sparse_l2_threshold_diffuse_high_endpoints128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseHighEndpoints128

axiom sparse_l2_threshold_dominant_direct_cover192_bits128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantDirectCover192Bits128
axiom sparse_l2_threshold_dominant_capped_fourier_cover192_bits128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantCappedFourierCover192Bits128
axiom sparse_l2_threshold_dominant_singleton_fourier_cover192_bits128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantSingletonFourierCover192Bits128
axiom sparse_l2_threshold_dominant_final_ratio192_bits128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantFinalRatio192Bits128
axiom sparse_l2_threshold_near_final_ratio192_bits128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearFinalRatio192Bits128
axiom sparse_l2_threshold_diffuse_final_ratio192_bits128_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseFinalRatio192Bits128

axiom sparse_l2_threshold_dominant_direct_cover256_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantDirectCover256Bits192
axiom sparse_l2_threshold_dominant_capped_fourier_cover256_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantCappedFourierCover256Bits192
axiom sparse_l2_threshold_dominant_singleton_fourier_cover256_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantSingletonFourierCover256Bits192
axiom sparse_l2_threshold_dominant_final_ratio256_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantFinalRatio256Bits192
axiom sparse_l2_threshold_near_final_ratio256_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearFinalRatio256Bits192
axiom sparse_l2_threshold_diffuse_final_ratio256_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseFinalRatio256Bits192

axiom sparse_l2_threshold_dominant_direct_cover384_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantDirectCover384Bits192
axiom sparse_l2_threshold_dominant_capped_fourier_cover384_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantCappedFourierCover384Bits192
axiom sparse_l2_threshold_dominant_singleton_fourier_cover384_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantSingletonFourierCover384Bits192
axiom sparse_l2_threshold_dominant_final_ratio384_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantFinalRatio384Bits192
axiom sparse_l2_threshold_near_final_ratio384_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearFinalRatio384Bits192
axiom sparse_l2_threshold_diffuse_final_ratio384_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseFinalRatio384Bits192


axiom sparse_l2_threshold_dominant_direct_cover512_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantDirectCover512Bits192
axiom sparse_l2_threshold_dominant_capped_fourier_cover512_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantCappedFourierCover512Bits192
axiom sparse_l2_threshold_dominant_singleton_fourier_cover512_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantSingletonFourierCover512Bits192
axiom sparse_l2_threshold_dominant_final_ratio512_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantFinalRatio512Bits192
axiom sparse_l2_threshold_near_final_ratio512_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearFinalRatio512Bits192
axiom sparse_l2_threshold_diffuse_final_ratio512_bits192_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseFinalRatio512Bits192

axiom sparse_l2_threshold_dominant_direct_cover512_floor73_bits193_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantDirectCover512Floor73Bits193
axiom sparse_l2_threshold_dominant_capped_fourier_cover512_floor73_bits193_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantCappedFourierCover512Floor73Bits193
axiom sparse_l2_threshold_dominant_singleton_fourier_cover512_floor73_bits193_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantSingletonFourierCover512Floor73Bits193
axiom sparse_l2_threshold_dominant_final_ratio512_floor73_bits193_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantFinalRatio512Floor73Bits193
axiom sparse_l2_threshold_near_final_ratio512_floor73_bits193_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearFinalRatio512Floor73Bits193
axiom sparse_l2_threshold_diffuse_floor73_endpoints_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseFloor73Endpoints
axiom sparse_l2_threshold_diffuse_final_ratio512_floor73_bits193_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseFinalRatio512Floor73Bits193

axiom sparse_l2_threshold_dominant_direct_cover512_bits256_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantDirectCover512Bits256
axiom sparse_l2_threshold_dominant_capped_fourier_cover512_bits256_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantCappedFourierCover512Bits256
axiom sparse_l2_threshold_dominant_singleton_fourier_cover512_bits256_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantSingletonFourierCover512Bits256
axiom sparse_l2_threshold_dominant_final_ratio512_bits256_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDominantFinalRatio512Bits256
axiom sparse_l2_threshold_near_final_ratio512_bits256_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdNearFinalRatio512Bits256
axiom sparse_l2_threshold_diffuse_final_ratio512_bits256_assumed :
  CertifiedJL.CertificateContracts.SparseL2ThresholdDiffuseFinalRatio512Bits256

end CertifiedJLFast.Assumptions
