/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap47Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap47Diffuse

private def globalLeaf06BernsteinNumerators : List ℤ :=
  [
    (2231847934189834692121152678115200 : ℤ), (2292073624785313166276397093575400 : ℤ), (2354405387959929173169660025465800 : ℤ),
    (2418819150957267413962346124097440 : ℤ), (2484937056040556705562170806944880 : ℤ), (2551962365601874517108403103553400 : ℤ),
    (2618657937716652997250398590887400 : ℤ), (2683381320571642625978177248356900 : ℤ), (2744183148205009899974667626258280 : ℤ),
    (2798966781869019738772769065998216 : ℤ), (2845697092425269834355638084060250 : ℤ), (2882636424352697991000308831875440 : ℤ),
    (2908577874432703095515761409887830 : ℤ), (2923041776150288779789064113532538 : ℤ), (2926402054454034761308862376958376 : ℤ),
    (2919915562412355789924936190276380 : ℤ), (2905639349603861075339561917834760 : ℤ), (2886236717352896474449145278801240 : ℤ),
    (2864690611186941801537994069934364 : ℤ), (2843959455674299695465505896325320 : ℤ), (2826622847747226078812165517705780 : ℤ),
    (2814569904347744259739237531533000 : ℤ), (2808779823838132849840824721962160 : ℤ), (2809232141754365131300723150599170 : ℤ),
    (2814964680577951358030460933163128 : ℤ), (2824273300936442275689722167371200 : ℤ), (2835023346003679477879151959988000 : ℤ),
    (2845022592192649572195388321629750 : ℤ), (2852393546206541887266388968751455 : ℤ), (2855881710926582520680450557330635 : ℤ),
    (2855046700692187871721708710625525 : ℤ), (2850303359200519001216201936268175 : ℤ), (2842806856666553548104012024105400 : ℤ),
    (2834204242353701808017724194488536 : ℤ), (2826299721614291598187777604407464 : ℤ), (2820697168787862889612601325235270 : ℤ),
    (2818487758251695523510067105852080 : ℤ), (2820042023329404995796881653240920 : ℤ), (2824945612307838505823391784016280 : ℤ),
    (2832090311944946273575791741004818 : ℤ), (2839901978134666199556607562462680 : ℤ), (2846660799607900159334031207676440 : ℤ),
    (2850852045751874753193657660133890 : ℤ), (2851480486776057072693350603330776 : ℤ), (2848289820235894256846714042362982 : ℤ),
    (2841847762835395156937417701017750 : ℤ), (2833483781465873175429985020153240 : ℤ), (2825094259470009163542342385788450 : ℤ),
    (2818853667381952242614010481481160 : ℤ), (2816885583861178685238703323932824 : ℤ), (2820951721150183887874235208448700 : ℤ),
    (2832210338725011811561435271238450 : ℤ), (2851079676910727214265896625023800 : ℤ), (2877221012986900126957072147270240 : ℤ),
    (2909634060056610045377374684704540 : ℤ), (2946838885529891909466287292764850 : ℤ), (2987106465767188007056454835994800 : ℤ),
    (3028695990905146938150955482502200 : ℤ)
  ]

private abbrev globalLeaf06BernsteinDenominator : ℤ := 2831885495259272852400000000000000

private def globalLeaf06Bernstein : List ℚ :=
  globalLeaf06BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf06BernsteinDenominator

theorem globalLeaf06BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf06Bernstein globalLeaf06BernsteinNumerators
      globalLeaf06BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf06BernsteinScale : ∀ k ≤ degree,
    globalLeaf06Bernstein.getD k 0 * globalLeaf06BernsteinDenominator =
      globalLeaf06BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf06BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf06IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (0 : ℤ) (1 : ℤ)
      (2 : ℤ) degree
      globalLeaf06BernsteinNumerators globalLeaf06BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf06NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf06Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf06Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (0 : ℚ) (1 / 2 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf06Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf06Bernstein, globalLeaf06BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf06BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf06IdentityCheck

theorem globalLeaf06Nonneg {y : ℝ}
    (hlo : (((0 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((1 / 2 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf06Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf06NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf06Tree :
    NonnegativeTree (rationalPowerValue (power))
      (0 : ℚ) (1 / 2 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf06Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap47Diffuse
