/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap47Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap47Diffuse

private def globalLeaf05BernsteinNumerators : List ℤ :=
  [
    (404269375111926116595307899193800 : ℤ), (406959110274987370784499377562000 : ℤ), (408553688656735348581778835661750 : ℤ),
    (409014865133828459639491270627260 : ℤ), (408571028334020649557433390668160 : ℤ), (407724909933834219297531360017800 : ℤ),
    (407195835229613561921507142590550 : ℤ), (407797511973479959417975132799100 : ℤ), (410267426364735251106232841560248 : ℤ),
    (415077881782563191610723456456840 : ℤ), (422268120301235797571588710544550 : ℤ), (431338908093527073648283307090520 : ℤ),
    (441243888954293616210845741200230 : ℤ), (450496268386161680323879012711222 : ℤ), (457387403678985983486126347267764 : ℤ),
    (460289799471279126837890243928450 : ℤ), (457995945844179174943585658795640 : ℤ), (450031333700280254405826087359160 : ℤ),
    (436878459741052919250792761910462 : ℤ), (420060026538452094720282846535800 : ℤ), (402052416290895422265632813492760 : ℤ),
    (386030803259860846137035328732480 : ℤ), (375479050779647734163524008742090 : ℤ), (373724304620702300936314750548904 : ℤ),
    (383472297909646340746477533520344 : ℤ), (406421326089870217568356735801400 : ℤ), (443020084967901719721634818902275 : ℤ),
    (492409603816400215371426349216725 : ℤ), (552557332304017069968159844719915 : ℤ), (620558378356207595297525422913295 : ℤ),
    (693051230830052903463814335655050 : ℤ), (766677995107558147652451819744000 : ℤ), (838514929332088453166125559262800 : ℤ),
    (906407963676232937734761128781720 : ℤ), (969167523690062779603336348080350 : ℤ), (1026603156849020383215135226963520 : ℤ),
    (1079406098116090130593950764817600 : ℤ), (1128912063120524552672458017888660 : ℤ), (1176793313428082027653988696637312 : ℤ),
    (1224736129485385208296054382886876 : ℤ), (1274156886322541412147571106880440 : ℤ), (1325998375595649881281606165897480 : ℤ),
    (1380630638281983216652330709377020 : ℤ), (1437860883902901288298303404515128 : ℤ), (1497038633665400717897079005899682 : ℤ),
    (1557228007396725505291506627043110 : ℤ), (1617411005690226286234474986148140 : ℤ), (1676684387033733519796805247450330 : ℤ),
    (1734417744158884577745516153521544 : ℤ), (1790350100314461556926160246661800 : ℤ), (1844614633741112106608720765565100 : ℤ),
    (1897693699517068823108365454037000 : ℤ), (1950317104556986679357380252916200 : ℤ), (2003324113328051303028978280774960 : ℤ),
    (2057513152897227166708070330714160 : ℤ), (2113502625578015276548682363625000 : ℤ), (2171622243594356217965908262655000 : ℤ),
    (2231847934189834692121152678115200 : ℤ)
  ]

private abbrev globalLeaf05BernsteinDenominator : ℤ := 2831885495259272852400000000000000

private def globalLeaf05Bernstein : List ℚ :=
  globalLeaf05BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf05BernsteinDenominator

theorem globalLeaf05BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf05Bernstein globalLeaf05BernsteinNumerators
      globalLeaf05BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05BernsteinScale : ∀ k ≤ degree,
    globalLeaf05Bernstein.getD k 0 * globalLeaf05BernsteinDenominator =
      globalLeaf05BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf05BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf05IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-1 : ℤ) (1 : ℤ)
      (2 : ℤ) degree
      globalLeaf05BernsteinNumerators globalLeaf05BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf05Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-1 / 2 : ℚ) (0 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf05Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf05Bernstein, globalLeaf05BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf05BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf05IdentityCheck

theorem globalLeaf05Nonneg {y : ℝ}
    (hlo : (((-1 / 2 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((0 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf05Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf05NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf05Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-1 / 2 : ℚ) (0 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf05Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap47Diffuse
