/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap47Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap47Diffuse

private def globalLeaf07BernsteinNumerators : List ℤ :=
  [
    (3028695990905146938150955482502200 : ℤ), (3070285516043105869245456129009600 : ℤ), (3113196986081727633844289878794450 : ℤ),
    (3155689591157660831950534899964560 : ℤ), (3196010735183760375737702664191920 : ℤ), (3232633340674886453827009441171400 : ℤ),
    (3264499903756050556145827687144050 : ℤ), (3291231413375249695676515860605600 : ℤ), (3313255246220106963097052405429944 : ℤ),
    (3331810204096348485047388348491112 : ℤ), (3348800548232101196928826812830370 : ℤ), (3366494210166556643093908361477940 : ℤ),
    (3387091234904842313688881932848870 : ℤ), (3412222531388628391991580170984694 : ℤ), (3442469658583435880447198953722648 : ℤ),
    (3477015822510875572277305348299270 : ℤ), (3513538665581527124713570295775320 : ℤ), (3548430753188110877557860053940120 : ℤ),
    (3577381646213909862414305065852434 : ℤ), (3596279440853434445711468775904308 : ℤ), (3602299820241776187193446149932680 : ℤ),
    (3594964094113799946517022357419680 : ℤ), (3576887065269369279113884006746630 : ℤ), (3553925899145125572784103842477100 : ℤ),
    (3534504770552783742541156788895800 : ℤ), (3528039454682949064061064864108600 : ℤ), (3542615729826830055547153810647375 : ℤ),
    (3582353791976301924276658265853525 : ℤ), (3645154607753296869334901431537995 : ℤ), (3721680132651347516615149101365175 : ℤ),
    (3796358799295775719927721595126150 : ℤ), (3850837670213832955521476781514800 : ℤ), (3869595142666276252607817652811200 : ℤ),
    (3846477381025067120267171176254600 : ℤ), (3789986592904009581623526925564450 : ℤ), (3724644676326121314928001379540540 : ℤ),
    (3686156769868447596043313679723000 : ℤ), (3709746124549012940921361715276860 : ℤ), (3813874131107231827316169483616536 : ℤ),
    (3984939479684269265852738922475716 : ℤ), (4171152863344466298248910704142360 : ℤ), (4293833197390410862558276816381160 : ℤ),
    (4280065171129544833505954297003100 : ℤ), (4110823769147360559136568069119776 : ℤ), (3863946455847677242270963025192474 : ℤ),
    (3716585231945625698362365261387150 : ℤ), (3869795820822357557160633718171200 : ℤ), (4390371427895696044771785304482270 : ℤ),
    (5048653825078217679136314485111112 : ℤ), (5335484455727526771863986586803304 : ℤ), (4835796424703749091288612950664100 : ℤ),
    (3827732600343703796039026382322000 : ℤ), (3403220875994289876992097853621400 : ℤ), (4280884549738061293280585850928320 : ℤ),
    (4914161444163124208246145471316800 : ℤ), (2544088866935674067966643281595000 : ℤ), (4193485425563552647904284057348200 : ℤ),
    (2831942132966346152361788727147600 : ℤ)
  ]

private abbrev globalLeaf07BernsteinDenominator : ℤ := 2831885495259272852400000000000000

private def globalLeaf07Bernstein : List ℚ :=
  globalLeaf07BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf07BernsteinDenominator

theorem globalLeaf07BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf07Bernstein globalLeaf07BernsteinNumerators
      globalLeaf07BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf07BernsteinScale : ∀ k ≤ degree,
    globalLeaf07Bernstein.getD k 0 * globalLeaf07BernsteinDenominator =
      globalLeaf07BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf07BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf07IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (1 : ℤ) (1 : ℤ)
      (2 : ℤ) degree
      globalLeaf07BernsteinNumerators globalLeaf07BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf07NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf07Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf07Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (1 / 2 : ℚ) (1 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf07Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf07Bernstein, globalLeaf07BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf07BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf07IdentityCheck

theorem globalLeaf07Nonneg {y : ℝ}
    (hlo : (((1 / 2 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((1 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf07Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf07NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf07Tree :
    NonnegativeTree (rationalPowerValue (power))
      (1 / 2 : ℚ) (1 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf07Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap47Diffuse
