import CertifiedJL.Certificates.Families.L2Lower.Rows256Bits128.Near.Soundness.ThresholdNearCoarsePartition128

/-! Untrusted proposal generator. Its output contains only rational cells and
constructor trees; production proofs kernel-check all leaves and derive coverage
structurally. Run after building the partition module. -/

open CertifiedJL.ThresholdNearCoarse128

def renderPlan : Plan → String
  | .leaf => ".leaf"
  | .splitX l r => s!"(.splitX {renderPlan l} {renderPlan r})"
  | .splitA l r => s!"(.splitA {renderPlan l} {renderPlan r})"

def renderRat (q : Rat) : String := s!"({q.num} / {q.den})"

def renderCell (c : Cell) : String :=
  "{ xLower := " ++ renderRat c.xLower ++ ", xUpper := " ++ renderRat c.xUpper ++
    ", aLower := " ++ renderRat c.aLower ++ ", aUpper := " ++ renderRat c.aUpper ++ " }"

def main (args : List String) : IO Unit := do
  let output ← IO.mkRef ""
  let emit (line : String) : IO Unit := output.modify (· ++ line ++ "\n")
  let cases : List (String × Cell × Nat) := [
    ("ThresholdNearCoarseShard0000_00_00_0000_128", cell000000000000, 6),
    ("ThresholdNearCoarseShard0000_00_00_0001_128", cell000000000001, 6),
    ("ThresholdNearCoarseShard0000_00_00_0010_128", cell000000000010, 6),
    ("ThresholdNearCoarseShard0000_00_00_0011_128", cell000000000011, 6),
    ("ThresholdNearCoarseShard0000_00_00_01_128", cell0000000001, 8),
    ("ThresholdNearCoarseShard0000_00_00_10_128", cell0000000010, 8),
    ("ThresholdNearCoarseShard0000_00_00_11_128", cell0000000011, 8),
    ("ThresholdNearCoarseShard0000_00_01_128", cell00000001, 10),
    ("ThresholdNearCoarseShard0000_00_10_128", cell00000010, 10),
    ("ThresholdNearCoarseShard0000_00_11_128", cell00000011, 10),
    ("ThresholdNearCoarseShard0000_01_00_128", cell00000100, 10),
    ("ThresholdNearCoarseShard0000_01_01_128", cell00000101, 10),
    ("ThresholdNearCoarseShard0000_01_10_128", cell00000110, 10),
    ("ThresholdNearCoarseShard0000_01_11_128", cell00000111, 10),
    ("ThresholdNearCoarseShard0000_10_128", cell000010, 12),
    ("ThresholdNearCoarseShard0000_11_128", cell000011, 12),
    ("ThresholdNearCoarseShard0001_0000_128", cell00010000, 10),
    ("ThresholdNearCoarseShard0001_0001_128", cell00010001, 10),
    ("ThresholdNearCoarseShard0001_0010_128", cell00010010, 10),
    ("ThresholdNearCoarseShard0001_0011_128", cell00010011, 10),
    ("ThresholdNearCoarseShard0001_01_128", cell000101, 12),
    ("ThresholdNearCoarseShard0001_10_128", cell000110, 12),
    ("ThresholdNearCoarseShard0001_11_128", cell000111, 12),
    ("ThresholdNearCoarseShard0010_128", cell0010, 14),
    ("ThresholdNearCoarseShard0011_128", cell0011, 14),
    ("ThresholdNearCoarseShard0100_00_128", cell010000, 12),
    ("ThresholdNearCoarseShard0100_01_128", cell010001, 12),
    ("ThresholdNearCoarseShard0100_10_128", cell010010, 12),
    ("ThresholdNearCoarseShard0100_11_128", cell010011, 12),
    ("ThresholdNearCoarseShard0101_00_128", cell010100, 12),
    ("ThresholdNearCoarseShard0101_01_00_128", cell01010100, 10),
    ("ThresholdNearCoarseShard0101_01_01_00_128", cell0101010100, 8),
    ("ThresholdNearCoarseShard0101_01_01_0100_128", cell010101010100, 6),
    ("ThresholdNearCoarseShard0101_01_01_0101_128", cell010101010101, 6),
    ("ThresholdNearCoarseShard0101_01_01_0110_128", cell010101010110, 6),
    ("ThresholdNearCoarseShard0101_01_01_0111_128", cell010101010111, 6),
    ("ThresholdNearCoarseShard0101_01_01_10_128", cell0101010110, 8),
    ("ThresholdNearCoarseShard0101_01_01_11_128", cell0101010111, 8),
    ("ThresholdNearCoarseShard0101_01_10_128", cell01010110, 10),
    ("ThresholdNearCoarseShard0101_01_11_128", cell01010111, 10),
    ("ThresholdNearCoarseShard0101_10_128", cell010110, 12),
    ("ThresholdNearCoarseShard0101_11_128", cell010111, 12),
    ("ThresholdNearCoarseShard0110_128", cell0110, 14),
    ("ThresholdNearCoarseShard0111_128", cell0111, 14),
    ("ThresholdNearCoarseShard1000_128", cell1000, 14),
    ("ThresholdNearCoarseShard1001_128", cell1001, 14),
    ("ThresholdNearCoarseShard1010_128", cell1010, 14),
    ("ThresholdNearCoarseShard1011_128", cell1011, 14),
    ("ThresholdNearCoarseShard1100_128", cell1100, 14),
    ("ThresholdNearCoarseShard1101_128", cell1101, 14),
    ("ThresholdNearCoarseShard1110_128", cell1110, 14),
    ("ThresholdNearCoarseShard1111_128", cell1111, 14)]
  emit "import CertifiedJL.Certificates.Families.L2Lower.Rows256Bits128.Near.Data.ThresholdNearCoarsePlan128"
  emit ""
  emit "/-! Generated by scripts/GenerateNearCoarsePlans.lean. Raw proposals only."
  emit "Every production leaf still requires a kernel proof of planCheck = true. -/"
  emit ""
  emit "namespace CertifiedJL.ThresholdNearCoarse128"
  emit ""
  emit "set_option linter.style.longLine false"
  emit ""
  emit "def storedPlans : List (Cell × Plan) := ["
  for ((name, cell, depth), i) in cases.zipIdx do
    let plan := adaptiveRefine depth true cell
    unless planCheck cell plan do
      throw (IO.userError s!"proposal fails: {name}")
    emit s!"  -- {name}"
    emit ("  (" ++ renderCell cell ++ ", " ++ renderPlan plan ++ ")" ++
      (if i + 1 == cases.length then "]" else ","))
  emit ""
  emit "/-- A missing proposal returns a leaf, which must still pass the checker. -/"
  emit "def storedPlan (cell : Cell) : Plan :="
  emit "  match storedPlans.find? (fun entry => decide (entry.1 = cell)) with"
  emit "  | some entry => entry.2"
  emit "  | none => .leaf"
  emit ""
  emit "end CertifiedJL.ThresholdNearCoarse128"

  let payload ← output.get
  let path := "CertifiedJL/Certificates/Families/L2Lower/Rows256Bits128/Near/Data/" ++
    "ThresholdNearCoarsePlans128.lean"
  match args with
  | ["--check"] =>
      unless (← IO.FS.readFile path) == payload do
        throw (IO.userError "stored plans differ; regenerate with --write")
      IO.println "near-coarse plans reproduce exactly (52 proposals)"
  | ["--write"] => IO.FS.writeFile path payload
  | [] => IO.print payload
  | _ => throw (IO.userError "usage: GenerateNearCoarsePlans.lean [--check|--write]")
