#!/usr/bin/env python3
"""Emit the proved-prefix replay from the preserved raw rectangle endpoints.

This generator proposes data only. Lean still checks every retained chunk,
exact coverage, the new tail budget, and the semantic integral bridge.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "CertifiedJL/Certificates/Families/L2Upper/Rows512Bits192"
COUNTS = [15, 12, 10, 9, 8, 7, 6, 5, 4, 3]
PREFIX = "CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192"


def raw_chunks(box):
    path = BASE / "Data" / f"Box{box:02d}.lean"
    source = path.read_text()
    match = re.search(
        r"def chunks : List \(Interval \d+\) :=\s*\[(.*?)\]\s*\n\ndef expectedBound",
        source,
        re.S,
    )
    if match is None:
        raise ValueError(f"could not find raw chunks in {path.relative_to(ROOT)}")
    chunks = re.findall(r"⟨\s*(-?\d+)\s*,\s*(-?\d+)\s*⟩", match.group(1))
    if len(chunks) != 32:
        raise ValueError(f"expected exactly 32 raw chunks for box {box}")
    return chunks


def chunk_theorem(box, index, interval):
    lo, hi = interval
    return f"""theorem box_{box:02d}_chunk_{index:03d} :
    boxCellChunk (profileBox {box}) {25 * index} 25 =
      ⟨{lo},
        {hi}⟩ := by
  decide +kernel"""


def outputs():
    out = {}
    header = "/- Generated by scripts/generate_upper_short_tail.py. -/\n\n"
    for box, count in enumerate(COUNTS):
        blocks = [
            chunk_theorem(box, index, interval)
            for index, interval in enumerate(raw_chunks(box))
        ]
        for shard, start in enumerate(range(0, count, 8)):
            out[BASE / "ShortTail/Replay/Shards" / f"Box{box:02d}" / f"Shard{shard:02d}.lean"] = (
                header + f"import {PREFIX}.ShortTail.Numeric\n\n"
                "namespace CertifiedJL.SparseUpperContour.ShortTail.Internal\n"
                "set_option linter.style.longLine false\n\n" +
                "\n\n".join(blocks[start:min(start + 8, count)]) +
                "\n\nend CertifiedJL.SparseUpperContour.ShortTail.Internal\n")
        imports = f"import {PREFIX}.ShortTail.Soundness\nimport {PREFIX}.Data.Box{box:02d}\n"
        imports += "".join(f"import {PREFIX}.ShortTail.Replay.Shards.Box{box:02d}.Shard{s:02d}\n"
                           for s in range((count + 7) // 8))
        terms = ",\n    ".join(f"boxCellChunk (profileBox {box}) {25*i} 25" for i in range(count))
        names = ",\n    ".join(f"Internal.box_{box:02d}_chunk_{i:03d}" for i in range(count))
        out[BASE / "ShortTail/Replay" / f"Box{box:02d}.lean"] = header + imports + f"""
namespace CertifiedJL.SparseUpperContour.ShortTail

private def prefix{box:02d} : List (Interval contourPrecision) :=
  SparseUpperContourData.Box{box:02d}.chunks.take {count}

private theorem chunks{box:02d} : computedChunks (profileBox {box}) {count} = prefix{box:02d} := by
  change [
    {terms}] = prefix{box:02d}
  rw [{names}]
  rfl

private theorem budget{box:02d} :
    Interval.upperLTCheck (boundFrom (profileBox {box}) {count} prefix{box:02d})
      (profileBox {box}).target = true := by decide +kernel

theorem box{box:02d}_endpoint {{profile : ℝ}}
    (hp : profile ∈ Set.Icc ((profileBox {box}).profileLeft : ℝ)
      ((profileBox {box}).profileRight : ℝ)) :
    boxActualPrefactorValue (profileBox {box}) *
      (∫ frequency : ℝ in Set.Ioi 0,
        actualBoxQuadratureIntegrand (profileBox {box}) profile frequency) <
      ((profileBox {box}).target : ℝ) := by
  exact endpoint_lt (by norm_num [profileBox, firstBox, profileBoxes]) {count}
    (by decide) (by decide +kernel) prefix{box:02d} chunks{box:02d}
    (Interval.upperLTCheck_sound budget{box:02d}) hp

end CertifiedJL.SparseUpperContour.ShortTail
"""
    imports = f"import {PREFIX}.Soundness.HighProfile\n" + "".join(
        f"import {PREFIX}.ShortTail.Replay.Box{i:02d}\n" for i in range(10))
    cases = "\n".join(f"  · exact box{i:02d}_endpoint hp" for i in range(10))
    out[BASE / "ShortTail/Replay/Verified.lean"] = header + imports + f"""
namespace CertifiedJL.SparseUpperContour.ShortTail

theorem all_endpoints {{box : ProfileBox}} (hbox : box ∈ profileBoxes)
    {{profile : ℝ}} (hp : profile ∈ Set.Icc (box.profileLeft : ℝ) (box.profileRight : ℝ)) :
    boxActualPrefactorValue box *
      (∫ frequency : ℝ in Set.Ioi 0, actualBoxQuadratureIntegrand box profile frequency) <
      (box.target : ℝ) := by
  simp only [profileBoxes, List.mem_cons, List.not_mem_nil, or_false] at hbox
  rcases hbox with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
{cases}

end CertifiedJL.SparseUpperContour.ShortTail
"""
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = outputs()
    for path, content in expected.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"generated replay differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    actual = set((BASE / "ShortTail/Replay").rglob("*.lean"))
    if extra := actual - expected.keys():
        raise SystemExit(f"unexpected generated files (not removed): {sorted(extra)}")
    print(f"{'Checked' if args.check else 'Generated'} {len(expected)} files, "
          f"{sum(COUNTS)} chunks, {sum(COUNTS)*25} rectangles; unchanged endpoints.")


if __name__ == "__main__":
    main()
