#!/usr/bin/env python3
"""Generate the paper's result table, including explicit replay status."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "evidence" / "result-catalog.toml"
OUTPUT = ROOT / "paper" / "generated" / "formalization-table.tex"
ROWS_PER_TABLE = 6


def table_opening() -> list[str]:
    return [
        r"\begin{tabularx}{\textwidth}{@{}",
        r"  >{\raggedright\arraybackslash}p{.275\textwidth}",
        r"  >{\raggedright\arraybackslash}p{.155\textwidth}",
        r"  >{\raggedright\arraybackslash}X",
        r"  >{\raggedright\arraybackslash}p{.17\textwidth}@{}}",
        r"\toprule",
        r"Lean theorem & Paper statement & Exact scope & Status \\",
        r"\midrule",
    ]


def render() -> str:
    with CATALOG.open("rb") as source:
        records = tomllib.load(source)["result"]

    lines = [
        "% Generated by scripts/generate_formalization_table.py.",
        "% Source: evidence/result-catalog.toml. Do not edit by hand.",
        r"\begin{center}",
        r"\small",
    ]
    visible = [
        record
        for record in records
        if record["verification_class"]
        in {"kernel_checked", "native_attested", "replay_pending"}
    ]
    for offset in range(0, len(visible), ROWS_PER_TABLE):
        if offset:
            lines.extend([r"\par\medskip", r"\noindent"])
        lines.extend(table_opening())
        for record in visible[offset : offset + ROWS_PER_TABLE]:
            lean = record["lean"].removeprefix("CertifiedJL.")
            status = record["verification_class"]
            lines.extend(
                [
                    rf"\nolinkurl{{{lean}}}",
                    rf"  & \Cref{{{record['paper_locator']}}}",
                    rf"  & {record['paper_scope_tex']}",
                    rf"  & \nolinkurl{{{status}}} \\",
                ]
            )
        lines.extend([r"\bottomrule", r"\end{tabularx}"])
    lines.extend([r"\end{center}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed table does not match the catalog",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(f"stale generated table: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
