#!/usr/bin/env python3
"""Render deterministic human-readable counterexample coverage reports."""

from __future__ import annotations

import argparse
import csv
from fractions import Fraction
from io import StringIO
import math
from pathlib import Path
import sys

from counterexample_catalog import ROOT, load_catalogs, require_unique
from check_counterexample_catalog import check


MARKDOWN_PATH = ROOT / "docs" / "counterexample-coverage.md"
TSV_PATH = ROOT / "docs" / "counterexample-coverage.tsv"


def _fraction(numerator, denominator) -> str:
    numerator, denominator = int(numerator), int(denominator)
    return str(numerator) if denominator == 1 else f"{numerator}/{denominator}"


def _maps(catalogs):
    comparisons = require_unique(catalogs.comparisons["comparison"], "id", "comparison")
    result_to_comparison = {
        source_id: comparison for comparison in comparisons.values()
        for source_id in comparison.get("result_ids", [])
    }
    claim_to_comparison = {
        source_id: comparison for comparison in comparisons.values()
        for source_id in comparison.get("claim_ids", [])
    }
    return comparisons, result_to_comparison, claim_to_comparison


def render_markdown(catalogs) -> str:
    results = sorted(catalogs.results["result"], key=lambda record: record["id"])
    claims = sorted(catalogs.contract["claim"], key=lambda record: record["id"])
    comparisons, result_map, claim_map = _maps(catalogs)
    derived = sorted(catalogs.comparisons.get("derived", []), key=lambda record: record["id"])
    derived_by_id = {record["id"]: record for record in derived}
    positive_units = [record for record in comparisons.values() if record.get("result_ids")]
    negative_units = [record for record in comparisons.values() if record.get("claim_ids")]
    sampled = sum(record.get("classification") == "sampled_positive_family" for record in positive_units)
    q9_unit = comparisons["l2-lower-rows256-29-2128-margin-3-over-1"]
    witnesses = require_unique(catalogs.witnesses["witness"], "id", "witness")
    sparse_security = witnesses["ternary-sparse-upper-security"]
    q9_witness = witnesses["ternary-ones16-q9-b4"]
    excluded = _fraction(q9_unit["bracket_lower_excluded_numerator"], q9_unit["bracket_lower_excluded_denominator"])
    valid_point = _fraction(q9_unit["bracket_valid_point_numerator"], q9_unit["bracket_valid_point_denominator"])
    factor = Fraction(int(sparse_security["exact_factor_338_numerator"]), int(sparse_security["exact_factor_338_denominator"]))
    factor_budget = sparse_security["exact_factor_338_budget_bits"]
    recovered_unmasked = derived_by_id["unmasked-l2-lower-rows256-9-bits194"]
    recovered_l2_upper = derived_by_id["l2-upper-rows264-509-bits192"]
    recovered_linf_upper = derived_by_id["linf-upper-rows462-1358-over-100-bits256"]
    floor76 = derived_by_id["l2-lower-floor76-bits193-obstruction"]
    four_ninths_count = sum(record["rule_id"] == "four-ninths" for record in derived)
    zero_mask_count = sum(record["rule_id"] == "masked-lower-zero-mask" and record["id"].startswith("zero-mask-row-expanded-") for record in derived)
    singleton_derived_count = sum(record["rule_id"] == "singleton-binomial-specialization" for record in derived)

    lines = [
        "# Counterexample coverage",
        "",
        "<!-- Generated by scripts/render_counterexample_coverage.py; do not edit. -->",
        "",
        "This report replaces the historical three-axis assignment inventory. It records reviewed coverage and open brackets; it does not claim that any unresolved optimum was found.",
        "",
        "## Inventory",
        "",
        f"- {len(results)} advertised positive results are covered by {len(positive_units)} optimization units.",
        f"- {len(claims)} substantive negative claims are covered by {len(negative_units)} reusable witness units and {len(catalogs.comparisons.get('claim_consequence', []))} distinct claim consequences.",
        f"- {sampled} replay-pending positive points remain grouped as sampled upper/lower families.",
        f"- {len(derived)} finite reviewed consequences are retained separately from advertised results.",
        "",
        "## Six quantitative families",
        "",
        "| Family | Statistic | Tail/event | Mask model | Modulus domain |",
        "|---|---|---|---|---|",
    ]
    for family in sorted(catalogs.families["family"], key=lambda record: record["id"]):
        lines.append(
            f"| `{family['id']}` | `{family['statistic']}` | `{family['tail']} / {family['event_comparison']}` | "
            f"`{family['mask_model']}` | `{family['modulus_domain']}` |"
        )

    rules = require_unique(catalogs.families["rule"], "id", "rule")
    lines += [
        "",
        "## Reviewed implication APIs",
        "",
        "| Rule | Lean declarations | Rule verification |",
        "|---|---|---|",
    ]
    for rule_id in ("upper-mask-optimum", "coordinate-lower-product", "coordinate-upper-product"):
        rule = rules[rule_id]
        declarations = list(rule.get("lean_declarations", []))
        if rule.get("generic_lean_declaration"):
            declarations.append(rule["generic_lean_declaration"])
        lines.append(
            f"| `{rule_id}` | {'<br>'.join(f'`{name}`' for name in declarations)} | `{rule['verification_class']}` |"
        )

    ceiling = factor_budget - math.log2(factor)
    lines += [
        "",
        "## Preserved endpoint information",
        "",
        f"- `ternary-ones16-q9-b4` excludes every rational multiplier in `(0, {excluded}]`; multiplier `{valid_point}` is a valid positive point. Its external arithmetic is `{q9_witness['mathematical_verification_class']}` and its source-matching Lean theorem is `{q9_witness['verification_class']}`. The real optimum is not asserted to be attained.",
        f"- The threshold-338 obstruction preserves the exact factor `({factor}) * 2^-{factor_budget}`, giving the reporting-only security ceiling "
        f"`{factor_budget} - log2({factor}) = {ceiling:.12f}` bits.",
        f"- The singleton family preserves its exact binomial numerator and the distinction between the kernel-checked floor-31 specialization and {singleton_derived_count} replay-pending public consequences from the generic Lean family.",
        f"- Derived records retain unmasked lower `{_fraction(recovered_unmasked['output_threshold_numerator'], recovered_unmasked['output_threshold_denominator'])}` at {recovered_unmasked['output_failure_budget'].removeprefix('2^-')} bits, "
        f"upper `{_fraction(recovered_l2_upper['output_threshold_numerator'], recovered_l2_upper['output_threshold_denominator'])}` at {recovered_l2_upper['output_rows']} rows and {recovered_l2_upper['output_failure_budget'].removeprefix('2^-')} bits, "
        f"coordinate upper `{_fraction(recovered_linf_upper['output_threshold_numerator'], recovered_linf_upper['output_threshold_denominator'])}` at {recovered_linf_upper['output_rows']} rows and {recovered_linf_upper['output_failure_budget'].removeprefix('2^-')} bits, "
        f"floor `{_fraction(floor76['output_threshold_numerator'], floor76['output_threshold_denominator'])}` failures at {floor76['source_budget_bits']} and {floor76['output_budget_bits']} bits, "
        f"{four_ninths_count} exact `fourNinths` consequences, and {zero_mask_count} row-expanded zero-mask specializations.",
        "",
        "## Authoritative source coverage",
        "",
        "| Kind | Source ID | Optimization/witness unit | Family/category | Axes | Status | Source verification | Comparison evidence |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for result in results:
        unit = result_map[result["id"]]
        lines.append(
            f"| positive | `{result['id']}` | `{unit['id']}` | `{unit['family']}` | "
            f"{', '.join(unit['axis'])} | `{unit['status']}` | `{result['verification_class']}` | `{unit['verification_class']}` |"
        )
    for claim in claims:
        unit = claim_map[claim["id"]]
        family = unit.get("family", unit.get("category"))
        lines.append(
            f"| negative | `{claim['id']}` | `{unit['id']}` | `{family}` | "
            f"{', '.join(unit['axis'])} | `{unit['status']}` | `{claim['verification_class']}` | `{unit['verification_class']}` |"
        )

    lines += [
        "",
        "## Reviewed finite consequences",
        "",
        "| Derived ID | Rule | Exact output | Verification |",
        "|---|---|---|---|",
    ]
    for record in derived:
        fields = []
        if "output_threshold_numerator" in record:
            fields.append(f"threshold={_fraction(record['output_threshold_numerator'], record['output_threshold_denominator'])}")
        if "output_rows" in record:
            fields.append(f"rows={record['output_rows']}")
        if "output_failure_budget" in record:
            fields.append(f"budget={record['output_failure_budget']}")
        if "output_budget_bits" in record:
            fields.append(f"budget=2^-{record['output_budget_bits']}")
        lines.append(
            f"| `{record['id']}` | `{record['rule_id']}` | {'; '.join(fields)} | `{record['verification_class']}` |"
        )
    return "\n".join(lines) + "\n"


def render_tsv(catalogs) -> str:
    results = sorted(catalogs.results["result"], key=lambda record: record["id"])
    claims = sorted(catalogs.contract["claim"], key=lambda record: record["id"])
    _, result_map, claim_map = _maps(catalogs)
    output = StringIO(newline="")
    writer = csv.writer(output, delimiter="\t", lineterminator="\n")
    writer.writerow(("source_kind", "source_id", "unit_id", "family_or_category", "axes", "classification", "status", "source_verification_class", "comparison_verification_class", "source_statistic", "source_event"))
    for result in results:
        unit = result_map[result["id"]]
        writer.writerow(("positive", result["id"], unit["id"], unit["family"], ",".join(unit["axis"]), unit["classification"], unit["status"], result["verification_class"], unit["verification_class"], result["statistic"], result["event_comparison"]))
    for claim in claims:
        unit = claim_map[claim["id"]]
        writer.writerow(("negative", claim["id"], unit["id"], unit.get("family", unit.get("category")), ",".join(unit["axis"]), unit["classification"], unit["status"], claim["verification_class"], unit["verification_class"], "not_applicable", "claim_statement"))
    return output.getvalue()


def rendered_documents(root: Path = ROOT) -> dict[Path, str]:
    catalogs = load_catalogs(root)
    return {
        root / "docs" / "counterexample-coverage.md": render_markdown(catalogs),
        root / "docs" / "counterexample-coverage.tsv": render_tsv(catalogs),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if committed reports are stale")
    args = parser.parse_args()
    check()
    documents = rendered_documents()
    stale = []
    for path, content in documents.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.write_text(content, encoding="utf-8")
    if stale:
        print(f"stale counterexample coverage reports: {', '.join(map(str, stale))}", file=sys.stderr)
        raise SystemExit(1)
    if not args.check:
        print("Rendered docs/counterexample-coverage.md and .tsv")


if __name__ == "__main__":
    main()
