/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse

private def globalLeaf03BernsteinNumerators : List ℤ :=
  [
    (6648675604425912720 : ℤ), (8408833772758474500 : ℤ), (10433812512123402792 : ℤ),
    (12716613176558099524 : ℤ), (15243677923923288016 : ℤ), (17996580192270120715 : ℤ),
    (20953860625771822346 : ℤ), (24092794871447283899 : ℤ), (27390955991808837968 : ℤ),
    (30827493144859899624 : ℤ), (34384092534719240160 : ℤ), (38045618955872913312 : ℤ),
    (41800458750382639360 : ℤ), (45640599591588059008 : ℤ), (49561490858749825792 : ℤ),
    (53561731894913726720 : ℤ), (57642635349381767168 : ℤ), (61807710106616821760 : ℤ),
    (66062103831410171904 : ℤ), (70412039597412925440 : ℤ), (74864274958038466560 : ℤ)
  ]

private abbrev globalLeaf03BernsteinDenominator : ℤ := 635043840000000000000

private def globalLeaf03Bernstein : List ℚ :=
  globalLeaf03BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf03BernsteinDenominator

theorem globalLeaf03BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf03Bernstein globalLeaf03BernsteinNumerators
      globalLeaf03BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf03BernsteinScale : ∀ k ≤ degree,
    globalLeaf03Bernstein.getD k 0 * globalLeaf03BernsteinDenominator =
      globalLeaf03BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf03BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf03IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-3 : ℤ) (1 : ℤ)
      (4 : ℤ) degree
      globalLeaf03BernsteinNumerators globalLeaf03BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf03NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf03Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf03Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-3 / 4 : ℚ) (-1 / 2 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf03Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf03Bernstein, globalLeaf03BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf03BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf03IdentityCheck

theorem globalLeaf03Nonneg {y : ℝ}
    (hlo : (((-3 / 4 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((-1 / 2 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf03Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf03NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf03Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-3 / 4 : ℚ) (-1 / 2 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf03Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse
