/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse

private def globalLeaf01BernsteinNumerators : List ℤ :=
  [
    (4571534857228654894410000 : ℤ), (4039241293003383761869620 : ℤ), (4043621950254842431065576 : ℤ),
    (4421766121648081504532740 : ℤ), (5036996970338905387736272 : ℤ), (5776440035580296768339635 : ℤ),
    (6548756453358411016169066 : ℤ), (7282032072631839801558347 : ℤ), (7921814032257122865359120 : ℤ),
    (8429286734470995035174160 : ℤ), (8779579508260300565919360 : ℤ), (8960198600469830234482656 : ℤ),
    (8969576464453849474475776 : ℤ), (8815731635837604130134016 : ℤ), (8515032792881068935416320 : ℤ),
    (8091060895380869180084480 : ℤ), (7573563581351788398141440 : ℤ), (6997496275232738749472768 : ℤ),
    (6402144725391844286005248 : ℤ), (5830323942581990889603072 : ℤ), (5327648755034870149939200 : ℤ)
  ]

private abbrev globalLeaf01BernsteinDenominator : ℤ := 42617070692597760000000000000

private def globalLeaf01Bernstein : List ℚ :=
  globalLeaf01BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf01BernsteinDenominator

theorem globalLeaf01BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf01Bernstein globalLeaf01BernsteinNumerators
      globalLeaf01BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf01BernsteinScale : ∀ k ≤ degree,
    globalLeaf01Bernstein.getD k 0 * globalLeaf01BernsteinDenominator =
      globalLeaf01BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf01BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf01IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-15 : ℤ) (1 : ℤ)
      (16 : ℤ) degree
      globalLeaf01BernsteinNumerators globalLeaf01BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf01NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf01Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf01Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-15 / 16 : ℚ) (-7 / 8 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf01Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf01Bernstein, globalLeaf01BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf01BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf01IdentityCheck

theorem globalLeaf01Nonneg {y : ℝ}
    (hlo : (((-15 / 16 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((-7 / 8 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf01Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf01NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf01Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-15 / 16 : ℚ) (-7 / 8 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf01Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse
