/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse

private def globalLeaf00BernsteinNumerators : List ℤ :=
  [
    (474823558419957703161937920 : ℤ), (399216586825035390721720320 : ℤ), (333663749044700032171769856 : ℤ),
    (277089921824235004767502336 : ℤ), (228510587378458547785302016 : ℤ), (187025810220113497402900480 : ℤ),
    (151814542573391437296041984 : ℤ), (122129243364913933322289152 : ℤ), (97290796361711879571636224 : ℤ),
    (76683713584393736676630528 : ℤ), (59751610664263239099740160 : ℤ), (45992941336115598934924416 : ℤ),
    (34956978764277063061140352 : ℤ), (26240031888614866755058309 : ℤ), (19481885450182546754042566 : ℤ),
    (14362452813319147084509965 : ℤ), (10598631142820669627780336 : ℤ), (7941348921669607094705276 : ℤ),
    (6172796207155926961227096 : ℤ), (5103828421453926026950380 : ℤ), (4571534857228654894410000 : ℤ)
  ]

private abbrev globalLeaf00BernsteinDenominator : ℤ := 42617070692597760000000000000

private def globalLeaf00Bernstein : List ℚ :=
  globalLeaf00BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf00BernsteinDenominator

theorem globalLeaf00BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf00Bernstein globalLeaf00BernsteinNumerators
      globalLeaf00BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf00BernsteinScale : ∀ k ≤ degree,
    globalLeaf00Bernstein.getD k 0 * globalLeaf00BernsteinDenominator =
      globalLeaf00BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf00BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf00IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-16 : ℤ) (1 : ℤ)
      (16 : ℤ) degree
      globalLeaf00BernsteinNumerators globalLeaf00BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf00NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf00Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf00Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-1 : ℚ) (-15 / 16 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf00Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf00Bernstein, globalLeaf00BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf00BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf00IdentityCheck

theorem globalLeaf00Nonneg {y : ℝ}
    (hlo : (((-1 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((-15 / 16 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf00Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf00NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf00Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-1 : ℚ) (-15 / 16 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf00Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse
