/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse

private def globalLeaf02BernsteinNumerators : List ℤ :=
  [
    (650347748417342547600 : ℤ), (527624313957596273268 : ℤ), (438663377184731178984 : ℤ),
    (428010668793758582788 : ℤ), (545680312992982200784 : ℤ), (844305433340107045075 : ℤ),
    (1376848263566582227754 : ℤ), (2194795008515603737163 : ℤ), (3346768326465249534416 : ℤ),
    (4877497315252383419376 : ℤ), (6827091319885222245120 : ℤ), (9230569775967644238432 : ℤ),
    (12117605696659736219392 : ℤ), (15512445334701016801792 : ℤ), (19433971037151837803008 : ℤ),
    (23895878389243805354240 : ℤ), (28906942443762446753792 : ℤ), (34471351180875118125056 : ℤ),
    (40589087365951017517056 : ℤ), (47256342693966903951360 : ℤ), (54465950551457077002240 : ℤ)
  ]

private abbrev globalLeaf02BernsteinDenominator : ℤ := 5202279137280000000000000

private def globalLeaf02Bernstein : List ℚ :=
  globalLeaf02BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf02BernsteinDenominator

theorem globalLeaf02BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf02Bernstein globalLeaf02BernsteinNumerators
      globalLeaf02BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf02BernsteinScale : ∀ k ≤ degree,
    globalLeaf02Bernstein.getD k 0 * globalLeaf02BernsteinDenominator =
      globalLeaf02BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf02BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf02IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-7 : ℤ) (1 : ℤ)
      (8 : ℤ) degree
      globalLeaf02BernsteinNumerators globalLeaf02BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf02NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf02Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf02Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-7 / 8 : ℚ) (-3 / 4 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf02Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf02Bernstein, globalLeaf02BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf02BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf02IdentityCheck

theorem globalLeaf02Nonneg {y : ℝ}
    (hlo : (((-7 / 8 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((-3 / 4 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf02Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf02NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf02Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-7 / 8 : ℚ) (-3 / 4 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf02Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse
