/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse

private def globalLeaf04BernsteinNumerators : List ℤ :=
  [
    (9138705439213680 : ℤ), (10225676962803900 : ℤ), (11362599460331028 : ℤ),
    (12556072105050322 : ℤ), (13813737976002736 : ℤ), (15142171053727615 : ℤ),
    (16544938546999064 : ℤ), (18021281660072681 : ℤ), (19565667031996616 : ℤ),
    (21168236116263060 : ℤ), (22815988891143540 : ℤ), (24494415583808928 : ℤ),
    (26189244644208232 : ℤ), (27887999064421828 : ℤ), (29581128126964078 : ℤ),
    (31262585057723840 : ℤ), (32929830132335792 : ℤ), (34583334223741856 : ℤ),
    (36225725949392268 : ℤ), (37860759661880970 : ℤ), (39492281526810000 : ℤ)
  ]

private abbrev globalLeaf04BernsteinDenominator : ℤ := 77520000000000000

private def globalLeaf04Bernstein : List ℚ :=
  globalLeaf04BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf04BernsteinDenominator

theorem globalLeaf04BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf04Bernstein globalLeaf04BernsteinNumerators
      globalLeaf04BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf04BernsteinScale : ∀ k ≤ degree,
    globalLeaf04Bernstein.getD k 0 * globalLeaf04BernsteinDenominator =
      globalLeaf04BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf04BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf04IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (-1 : ℤ) (1 : ℤ)
      (2 : ℤ) degree
      globalLeaf04BernsteinNumerators globalLeaf04BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf04NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf04Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf04Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (-1 / 2 : ℚ) (0 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf04Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf04Bernstein, globalLeaf04BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf04BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf04IdentityCheck

theorem globalLeaf04Nonneg {y : ℝ}
    (hlo : (((-1 / 2 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((0 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf04Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf04NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf04Tree :
    NonnegativeTree (rationalPowerValue (power))
      (-1 / 2 : ℚ) (0 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf04Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse
