/- This file is generated by scripts/derive_ternary_linf_frontiers.py. -/

import CertifiedJL.Certificates.Families.LInfLower.TwoDecimal.Replay.Cap24Diffuse.PowerScale

open scoped BigOperators Polynomial
open CertifiedJL.TrigonometricBernstein

set_option linter.style.longLine false

namespace CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse

private def globalLeaf05BernsteinNumerators : List ℤ :=
  [
    (9873070381702500 : ℤ), (10688831314167015 : ℤ), (11501080399071858 : ℤ),
    (12317509967621105 : ℤ), (13146179603051216 : ℤ), (13987244763546155 : ℤ),
    (14824654800816478 : ℤ), (15623492175772021 : ℤ), (16338624672717820 : ℤ),
    (16935979489326255 : ℤ), (17419022231285130 : ℤ), (17843425407332793 : ℤ),
    (18299420681050088 : ℤ), (18852091015414643 : ℤ), (19459526730524150 : ℤ),
    (19931526151826365 : ℤ), (20021771133818260 : ℤ), (19707141426586999 : ℤ),
    (19496666322416034 : ℤ), (20065501327928961 : ℤ), (19381938000000000 : ℤ)
  ]

private abbrev globalLeaf05BernsteinDenominator : ℤ := 19380000000000000

private def globalLeaf05Bernstein : List ℚ :=
  globalLeaf05BernsteinNumerators.map fun numerator =>
    (numerator : ℚ) / globalLeaf05BernsteinDenominator

theorem globalLeaf05BernsteinScaleCheck :
    integerScaleBlockCheck globalLeaf05Bernstein globalLeaf05BernsteinNumerators
      globalLeaf05BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05BernsteinScale : ∀ k ≤ degree,
    globalLeaf05Bernstein.getD k 0 * globalLeaf05BernsteinDenominator =
      globalLeaf05BernsteinNumerators.getD k 0 := by
  intro k hk
  exact integerScaleBlockCheck_sound globalLeaf05BernsteinScaleCheck
    k (by omega) (by simpa [degree] using Nat.lt_succ_iff.mpr hk)

set_option maxHeartbeats 40000000 in
-- The quadratic identity check now uses common-denominator integer arithmetic.
set_option maxRecDepth 1000000 in
theorem globalLeaf05IdentityCheck :
    integerBernsteinIdentityBlockCheck powerNumerators powerDenominator
      (0 : ℤ) (1 : ℤ)
      (1 : ℤ) degree
      globalLeaf05BernsteinNumerators globalLeaf05BernsteinDenominator 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05NonnegativeCheck :
    nonnegativeBlockCheck globalLeaf05Bernstein 0 (degree + 1) = true := by
  decide +kernel

theorem globalLeaf05Identity :
    affinePullbackQ (powerPolynomialQ (power))
        (0 : ℚ) (1 : ℚ) =
      bernsteinPolynomialQ degree globalLeaf05Bernstein := by
  apply affinePullbackQ_eq_bernsteinPolynomialQ_of_integerCertificate
    (by simp [degree, power])
    (by simp [degree, globalLeaf05Bernstein, globalLeaf05BernsteinNumerators])
    (by simp [degree, powerNumerators]) powerIntegerScale globalLeaf05BernsteinScale
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    globalLeaf05IdentityCheck

theorem globalLeaf05Nonneg {y : ℝ}
    (hlo : (((0 : ℚ)) : ℝ) ≤ y) (hhi : y ≤ (((1 : ℚ)) : ℝ)) :
    0 ≤ rationalPowerValue (power) y := by
  apply rationalPowerValue_nonneg_on_interval (by norm_num) hlo hhi globalLeaf05Identity
  intro k hk
  exact nonnegativeBlockCheck_sound globalLeaf05NonnegativeCheck
    k (by omega) (by simpa [degree] using hk)

theorem globalLeaf05Tree :
    NonnegativeTree (rationalPowerValue (power))
      (0 : ℚ) (1 : ℚ) :=
  .leaf (fun _y hlo hhi => globalLeaf05Nonneg hlo hhi)

end CertifiedJL.TernaryLInfTwoDecimal.Cap24Diffuse
