/-
Copyright (c) 2026 Anonymous Author. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Anonymous Author
-/

import CertifiedJL.Model.Distributions.Entry
import CertifiedJL.Probability.Finite.Conditioning

/-!
# Coordinate partitions of sparse-row seeds

This module exposes a sparse-row seed as the product of its coordinates in a
decidable mask and its coordinates outside that mask.  It also provides the
finite conditional-average inequality and exact dot-product decomposition
needed to condition one-row events on a selected coordinate block.
-/

open scoped BigOperators ENNReal

namespace CertifiedJL

section SparseSeedPartition

variable {d : ℕ} (mask : Fin d → Prop) [DecidablePred mask]

/-- Sparse-row seed coordinates selected by `mask`. -/
abbrev SparseRowSeedPart := {i : Fin d // mask i} → Bool × Bool

/-- Sparse-row seed coordinates outside `mask`. -/
abbrev SparseRowSeedCompl := {i : Fin d // ¬ mask i} → Bool × Bool

/-- Split a sparse-row seed into the selected and complementary coordinates. -/
def sparseRowSeedPartitionEquiv :
    SparseRowSeed d ≃ SparseRowSeedPart mask × SparseRowSeedCompl mask :=
  Probability.piSplitEquiv mask

/-- Split a sparse-row seed with the complementary block first. -/
def sparseRowSeedPartitionComplFirstEquiv :
    SparseRowSeed d ≃ SparseRowSeedCompl mask × SparseRowSeedPart mask :=
  (sparseRowSeedPartitionEquiv mask).trans
    (Equiv.prodComm (SparseRowSeedPart mask) (SparseRowSeedCompl mask))

/-- Reassemble a sparse-row seed from a coordinate partition. -/
def joinSparseRowSeed
    (selected : SparseRowSeedPart mask) (other : SparseRowSeedCompl mask) :
    SparseRowSeed d :=
  (sparseRowSeedPartitionEquiv mask).symm (selected, other)

@[simp]
theorem joinSparseRowSeed_selected
    (selected : SparseRowSeedPart mask) (other : SparseRowSeedCompl mask)
    (i : {i : Fin d // mask i}) :
    joinSparseRowSeed mask selected other i = selected i := by
  simp [joinSparseRowSeed, sparseRowSeedPartitionEquiv,
    Probability.piSplitEquiv, i.2]

@[simp]
theorem joinSparseRowSeed_compl
    (selected : SparseRowSeedPart mask) (other : SparseRowSeedCompl mask)
    (i : {i : Fin d // ¬ mask i}) :
    joinSparseRowSeed mask selected other i = other i := by
  simp [joinSparseRowSeed, sparseRowSeedPartitionEquiv,
    Probability.piSplitEquiv, i.2]

/-- The selected-coordinate contribution to a sparse-row integer dot product. -/
def sparseRowSeedPartDot
    (selected : SparseRowSeedPart mask) (w : Fin d → ℤ) : ℤ :=
  ∑ i, sparseBit (selected i) * w i

/-- The complementary-coordinate contribution to a sparse-row integer dot product. -/
def sparseRowSeedComplDot
    (other : SparseRowSeedCompl mask) (w : Fin d → ℤ) : ℤ :=
  ∑ i, sparseBit (other i) * w i

/-- Reassembly splits the sparse-row dot product into its two masked sums. -/
theorem sparseRow_join_dot_eq_add
    (selected : SparseRowSeedPart mask) (other : SparseRowSeedCompl mask)
    (w : Fin d → ℤ) :
    (∑ i, sparseRow (joinSparseRowSeed mask selected other) i * w i) =
      sparseRowSeedPartDot mask selected w +
        sparseRowSeedComplDot mask other w := by
  rw [sparseRowSeedPartDot, sparseRowSeedComplDot]
  rw [← Fintype.sum_subtype_add_sum_subtype mask]
  congr 1 <;>
    apply Finset.sum_congr rfl <;>
    intro i _ <;>
    simp [sparseRow]

/-- A uniform sparse-row seed becomes a uniform product under the partition. -/
theorem map_uniformSparseRowSeed_partition :
    (PMF.uniformOfFintype (SparseRowSeed d)).map
        (sparseRowSeedPartitionEquiv mask) =
      PMF.uniformOfFintype
        (SparseRowSeedPart mask × SparseRowSeedCompl mask) :=
  map_uniformOfFintype_equiv (sparseRowSeedPartitionEquiv mask)

/-- A uniform sparse-row seed remains uniform under the complement-first split. -/
theorem map_uniformSparseRowSeed_partitionComplFirst :
    (PMF.uniformOfFintype (SparseRowSeed d)).map
        (sparseRowSeedPartitionComplFirstEquiv mask) =
      PMF.uniformOfFintype
        (SparseRowSeedCompl mask × SparseRowSeedPart mask) :=
  map_uniformOfFintype_equiv (sparseRowSeedPartitionComplFirstEquiv mask)

/-- The sparse-row distribution is generated by the uniform selected/complement product. -/
theorem sparseRademacherRow_eq_map_uniformPartition :
    sparseRademacherRow d =
      (PMF.uniformOfFintype
        (SparseRowSeedPart mask × SparseRowSeedCompl mask)).map
        (fun x => sparseRow (joinSparseRowSeed mask x.1 x.2)) := by
  rw [sparseRademacherRow_eq_map_uniformRowSeed]
  rw [← map_uniformSparseRowSeed_partition mask, PMF.map_comp]
  congr 1
  funext seed
  simp [joinSparseRowSeed, sparseRowSeedPartitionEquiv]

/--
The sparse-row distribution is also generated by sampling the complementary block
first and the selected block second.
-/
theorem sparseRademacherRow_eq_map_uniformPartitionComplFirst :
    sparseRademacherRow d =
      (PMF.uniformOfFintype
        (SparseRowSeedCompl mask × SparseRowSeedPart mask)).map
        (fun x => sparseRow (joinSparseRowSeed mask x.2 x.1)) := by
  rw [sparseRademacherRow_eq_map_uniformRowSeed]
  rw [← map_uniformSparseRowSeed_partitionComplFirst mask, PMF.map_comp]
  congr 1
  funext seed
  simp [sparseRowSeedPartitionComplFirstEquiv, joinSparseRowSeed,
    sparseRowSeedPartitionEquiv]

/--
The sparse-row event probability is the uniform average over selected seeds
of the conditional probabilities on the complementary coordinates.
-/
theorem sparseRademacherRow_eventProbability_toReal_eq_partitionAverage
    (event : (Fin d → ℤ) → Prop) :
    (eventProbability (sparseRademacherRow d) event).toReal =
      ∑ selected : SparseRowSeedPart mask,
        (Fintype.card (SparseRowSeedPart mask) : ℝ)⁻¹ *
          (eventProbability
            ((PMF.uniformOfFintype (SparseRowSeedCompl mask)).map
              (fun other => sparseRow
                (joinSparseRowSeed mask selected other))) event).toReal := by
  rw [sparseRademacherRow_eq_map_uniformPartition mask]
  exact Probability.eventProbability_map_uniform_prod_toReal
    (fun selected other =>
      sparseRow (joinSparseRowSeed mask selected other)) event

/--
A common bound for all complementary-coordinate conditional events bounds the
unconditional sparse-row event.
-/
theorem sparseRademacherRow_eventProbability_toReal_le_of_partition
    (event : (Fin d → ℤ) → Prop) (c : ℝ)
    (hbound : ∀ selected : SparseRowSeedPart mask,
      (eventProbability
        ((PMF.uniformOfFintype (SparseRowSeedCompl mask)).map
          (fun other => sparseRow
            (joinSparseRowSeed mask selected other))) event).toReal ≤ c) :
    (eventProbability (sparseRademacherRow d) event).toReal ≤ c := by
  rw [sparseRademacherRow_eq_map_uniformPartition mask]
  exact Probability.eventProbability_map_uniform_prod_toReal_le
    (fun selected other =>
      sparseRow (joinSparseRowSeed mask selected other)) event c hbound

/--
The sparse-row event probability averaged with the complementary seed fixed
and the selected coordinates sampled conditionally.
-/
theorem sparseRademacherRow_eventProbability_toReal_eq_complFirstAverage
    (event : (Fin d → ℤ) → Prop) :
    (eventProbability (sparseRademacherRow d) event).toReal =
      ∑ other : SparseRowSeedCompl mask,
        (Fintype.card (SparseRowSeedCompl mask) : ℝ)⁻¹ *
          (eventProbability
            ((PMF.uniformOfFintype (SparseRowSeedPart mask)).map
              (fun selected => sparseRow
                (joinSparseRowSeed mask selected other))) event).toReal := by
  rw [sparseRademacherRow_eq_map_uniformPartitionComplFirst mask]
  exact Probability.eventProbability_map_uniform_prod_toReal
    (fun other selected =>
      sparseRow (joinSparseRowSeed mask selected other)) event

/--
A common conditional bound with the complementary seed fixed bounds the
unconditional sparse-row event.
-/
theorem sparseRademacherRow_eventProbability_toReal_le_of_complFirst
    (event : (Fin d → ℤ) → Prop) (c : ℝ)
    (hbound : ∀ other : SparseRowSeedCompl mask,
      (eventProbability
        ((PMF.uniformOfFintype (SparseRowSeedPart mask)).map
          (fun selected => sparseRow
            (joinSparseRowSeed mask selected other))) event).toReal ≤ c) :
    (eventProbability (sparseRademacherRow d) event).toReal ≤ c := by
  rw [sparseRademacherRow_eq_map_uniformPartitionComplFirst mask]
  exact Probability.eventProbability_map_uniform_prod_toReal_le
    (fun other selected =>
      sparseRow (joinSparseRowSeed mask selected other)) event c hbound

end SparseSeedPartition

end CertifiedJL
