/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_03_chunk_008 :
    boxCellChunk (profileBox 3) 200 25 =
      ⟨0,
        304198517023191042346729527210118637320545769334852743151037204530612080635370378824482722363⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
