/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_03_chunk_000 :
    boxCellChunk (profileBox 3) 0 25 =
      ⟨0,
        653385135087984396866139323637440560439295995512167050317755141954533337295573519896627457020236414887206771929126461861219657048529246532026398472300816⟩ := by
  decide +kernel

theorem box_03_chunk_001 :
    boxCellChunk (profileBox 3) 25 25 =
      ⟨0,
        4807289629857534483803405011534249900279089462300401879650813679608470502626507956207087888582404629216025619941384796415655028706301551⟩ := by
  decide +kernel

theorem box_03_chunk_002 :
    boxCellChunk (profileBox 3) 50 25 =
      ⟨0,
        42427267648968007979314645933297263348800361459491229353774345583411393696837802813003480458442000560982⟩ := by
  decide +kernel

theorem box_03_chunk_003 :
    boxCellChunk (profileBox 3) 75 25 =
      ⟨0,
        21890941361505364853090233520925674443895877456561959000100593671427683744⟩ := by
  decide +kernel

theorem box_03_chunk_004 :
    boxCellChunk (profileBox 3) 100 25 =
      ⟨0,
        5023693827297848321613031618137253906031172430887⟩ := by
  decide +kernel

theorem box_03_chunk_005 :
    boxCellChunk (profileBox 3) 125 25 =
      ⟨0,
        5164146662653429906362553461743⟩ := by
  decide +kernel

theorem box_03_chunk_006 :
    boxCellChunk (profileBox 3) 150 25 =
      ⟨0,
        6906491225621015902464844⟩ := by
  decide +kernel

theorem box_03_chunk_007 :
    boxCellChunk (profileBox 3) 175 25 =
      ⟨0,
        62420080685745783968134038062831212087002421564⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
