/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_02_chunk_000 :
    boxCellChunk (profileBox 2) 0 25 =
      ⟨0,
        717768637812613504017422000274405183246097322271214124782982869066709315437363271418261773583010219720563992951092344936934760658143477968306986236929539⟩ := by
  decide +kernel

theorem box_02_chunk_001 :
    boxCellChunk (profileBox 2) 25 25 =
      ⟨0,
        4417772201888255328893542237987377915353459541654229608807367977233261660541774169191725769867026387458129713865060052959074349115508370⟩ := by
  decide +kernel

theorem box_02_chunk_002 :
    boxCellChunk (profileBox 2) 50 25 =
      ⟨0,
        34159722647805587187114999734635149451327586732120995303771859712352758073346432100660306980803959625004⟩ := by
  decide +kernel

theorem box_02_chunk_003 :
    boxCellChunk (profileBox 2) 75 25 =
      ⟨0,
        12872051095227539000565271158154476857830172216251640556115261003591095405⟩ := by
  decide +kernel

theorem box_02_chunk_004 :
    boxCellChunk (profileBox 2) 100 25 =
      ⟨0,
        951283475970843543767590014189596342036371779831⟩ := by
  decide +kernel

theorem box_02_chunk_005 :
    boxCellChunk (profileBox 2) 125 25 =
      ⟨0,
        36027220768555109759418293672⟩ := by
  decide +kernel

theorem box_02_chunk_006 :
    boxCellChunk (profileBox 2) 150 25 =
      ⟨0,
        9520228804629526⟩ := by
  decide +kernel

theorem box_02_chunk_007 :
    boxCellChunk (profileBox 2) 175 25 =
      ⟨0,
        22108417745528398011134⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
