/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_02_chunk_008 :
    boxCellChunk (profileBox 2) 200 25 =
      ⟨0,
        698232071329750436786501021082923458605413889943834⟩ := by
  decide +kernel

theorem box_02_chunk_009 :
    boxCellChunk (profileBox 2) 225 25 =
      ⟨0,
        44487763287800398828224946768044846119566768896936308825046801226782317659890232093172821287160115751⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
