/- Generated by scripts/generate_upper_short_tail.py. -/

import CertifiedJL.Certificates.Families.L2Upper.Rows512Bits192.ShortTail.Numeric

namespace CertifiedJL.SparseUpperContour.ShortTail.Internal
set_option linter.style.longLine false

theorem box_09_chunk_000 :
    boxCellChunk (profileBox 9) 0 25 =
      ⟨0,
        76360368110444974504845044783993872449244256073992619973093862406419175675101283602787204368119452066475481106301201060268847267084333491557017474500549⟩ := by
  decide +kernel

theorem box_09_chunk_001 :
    boxCellChunk (profileBox 9) 25 25 =
      ⟨0,
        41645911055256240507907099882944269197781933813151216273251666850671429813791723219722984623902203387468035804722178395858759871379653327592⟩ := by
  decide +kernel

theorem box_09_chunk_002 :
    boxCellChunk (profileBox 9) 50 25 =
      ⟨0,
        15896887680362068132985694936337321900423867563140077349876943180337500350182357738320584390269224865522326538274760⟩ := by
  decide +kernel

end CertifiedJL.SparseUpperContour.ShortTail.Internal
